<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->render('html/html_head.phtml') ?>
    </head>
    <body class="<?php echo $this->bodyClass() ?>">
        <noscript>
            <div class="noscript-notice"><p>
                <strong><?php echo Axis::translate('core')->__(
                    'Please enable JavaScript in your browser.'
                ) ?></strong>
            </p></div>
        </noscript>
        <?php echo $this->layout()->afterBodyBegin ?>
        <div class="wrapper">

            <?php echo $this->render('html/header_topbar.phtml') ?>

            <div class="header-container">
                <div class="header">
                    <?php echo $this->render('html/header.phtml') ?>
                </div>
            </div>

            <?php echo $this->crumbs() ?>
            <?php echo $this->navigation()->breadcrumbs() ?>

            <div class="middle-container-wrapper">
                <div class="middle-container">
                    <div class="middle layout-3columns">
                        <?php echo $this->layout()->beforeContent ?>
                        <div class="col-main-left">
                            <div class="col-main">
                                <?php echo $this->message() ?>
                                <?php echo $this->layout()->content ?>
                            </div>
                            <div class="col-left side-col">
                                <?php echo $this->layout()->left ?>
                            </div>
                        </div>
                        <div class="col-right side-col">
                            <?php echo $this->layout()->right ?>
                        </div>
                        <?php echo $this->layout()->afterContent ?>
                    </div>
                </div>
            </div>

            <div class="footer-container">
                <div class="footer">
                    <?php echo $this->render('html/footer.phtml') ?>
                </div>
            </div>

        </div>
        <?php echo $this->layout()->beforeBodyEnd ?>
    </body>
</html>