<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title></title>
<style>
body {
    padding:0.5cm;
    font: 1em Verdana, Tahoma, sans-serif;
}
table {
    border-collapse:collapse;
    width:20cm;
    margin: 0 auto 0 auto;
}
table tr td, table tr th{
    border: 1px solid #000;
    padding:0.1cm 0.7cm;
}
table tr td, table tr th {
    text-align:left;
}

.two-columns {
    margin-top: 0.5cm;
}

.two-columns td, .two-columns th {
    width: 50%;
}

.margin-top {
    margin-top: 0.6cm;
}
.four-columns td, .four-columns th {
    width: 25%;
}
.no-border td{
    border:none;
    height:0.5cm;
}
.no-top-border td{
    border-top: 0px solid !important;
}
.no-bottom-border td{
    border-bottom: 0px solid !important;
}
.a-right * {
    text-align:right;
}
.brown * {
    background-color: #E8E8E8;
}
.dark-brown * {
    background-color: #7D7A7A;
    color:#FFF;
}
.no-padding *{
    padding: 0;
}
.small-padding {
    padding: 0.2cm;
}
.upper-text {
    text-transform: uppercase;
}
#logo {
    text-align:left;
}
#logo img {
    border:none;
}
.small-text {
    font-size: 0.9em;
}
.small-text img{
    font-size: 1.1em;
}
.vertical-top td{
    vertical-align: top;
}
.three-columns td, .three-columns th {
    width: 33%;
}
.dashed-border td {
    border: 1px dashed #CCCCCC;
}
.tranparent-text {
    color: #C9C9C9;
    /*opacity:0.5;*/
}
.dashed-border .empty-cell, .empty-cell {
    border:none !important;

}
</style>
</head>
<body>

    <?php $i = 0;?>
    <?php function newPage(&$i) {
        if ($i > 0) {
            echo '<!-- Next page --><div style="page-break-before:always"></div>';
        }
        $i++;
    }
    ?>
    <?php foreach ($this->orders as $order) :?>
        <?php $this->order = $order;?>
        <?php $this->i = $i; ?>
        <?php if ($this->invoice == 'true') :?>
            <?php newPage($i); ?>
            <?php echo $this->render('sales/order/print/invoice.phtml');?>
        <?php endif; ?>
        <?php if ($this->packingslip == 'true') :?>
            <?php newPage($i); ?>
            <?php echo $this->render('sales/order/print/packingslip.phtml') ?>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php if ($this->label == 'true') :?>
        <?php // newPage($i); ?>
        <?php echo $this->render('sales/order/print/label.phtml') ?>
    <?php endif; ?>

    <script type="text/javascript">
        window.print();
    </script>
</body>
</html>