<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <head>
        <?php $this->companyEmail = $this->company['support_email']; ?>
        <?php echo $this->render('include/html_head.phtml'); ?>
    </head>

    <body>
        <div style="margin:0px; padding:0px; background-color:#ffffff; ">
        <table cellspacing="0" cellpadding="0" border="0" width="98%" style="margin:10px 0px; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; margin-bottom:10px;">
            <tr>
                <td align="center" valign="top">
                    <?php echo $this->render('include/header.phtml'); ?>

                    <table cellspacing="0" cellpadding="20" border="0" width="650" style="background:#fff;margin-top:10px;" class="content">
                        <tr>
                            <td style="padding:0px;text-align:left;">
                                <p style="margin: 1px 0 4px;"><strong>
                                    <?php echo $this->translate('account')->__(
                                        'Welcome, %s %s',
                                        $this->escape($this->customer->firstname),
                                        $this->escape($this->customer->lastname)
                                    ); ?>
                                </strong></p>
                                <p style="margin: 1px 0 4px;"><?php echo $this->translate('account')->__('You have been registered on %s', $this->siteName); ?></p>

                                <?php
                                    $loginLink = $this->href('account/auth', true, false);
                                    $loginWord = $this->translate('account')->__('Login');
                                ?>

                                <p style="margin: 1px 0 4px;"><?php echo $this->translate('core')->__(
                                    'You can %s to the account, using the following values',
                                    "<a href='{$this->href('account/auth', true, false)}'>{$loginWord}</a>"
                                ); ?>:</p>
                                <p style="margin: 1px 0 4px;"><?php echo $this->translate('account')->__('Email')?>: <?php echo $this->customer->email ?></p>
                                <p style="margin: 1px 0 4px;"><?php echo $this->translate('account')->__('Password')?>: <?php echo $this->password ?></p>
                            </td>
                        </tr>
                    </table>

                    <?php echo $this->render('include/footer_html.phtml'); ?>
                </td>
            </tr>
        </table>
        </div>
    </body>
</html>
