<?php echo $this->translate('account')->__('New customer was registered on %s', $this->siteName) ?>


<?php echo $this->translate('account')->__('Firstname') ?>: <?php echo $this->escape($this->customer->firstname) ?>

<?php echo $this->translate('account')->__('Lastname') ?>: <?php echo $this->escape($this->customer->lastname) ?>

<?php echo $this->translate('account')->__('Email') ?>: <?php echo $this->customer->email ?>

<?php $route = Axis::config('core/backend/route') ?>
<?php echo $this->translate('core')->__('See Details Info');?>: <?php echo $this->href("{$route}/customer_index/index/customerId/", true, false) . $this->customer->id ?>


<?php echo $this->render('include/footer_txt.phtml') ?>