<?php echo $this->translate('account')->__('Welcome, %s %s', $this->escape($this->customer->firstname), $this->escape($this->customer->lastname)); ?>


<?php echo $this->translate('account')->__('You have been registered on %s', $this->siteName); ?>

<?php echo $this->translate('core')->__('You can %s to the account, using the following values', $this->translate('account')->__('Login')); ?>:

<?php echo $this->translate('account')->__('Email')?>: <?php echo $this->customer->email ?>

<?php echo $this->translate('account')->__('Password')?>: <?php echo $this->password ?>


<?php echo $this->render('include/footer_txt.phtml'); ?>