<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <head>
        <?php echo $this->render('include/html_head.phtml'); ?>
    </head>

    <body>
        <div style="margin:0px; padding:0px; background-color:#ffffff; ">
        <table cellspacing="0" cellpadding="0" border="0" width="98%" style="margin:10px 0px; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; margin-bottom:10px;">
            <tr>
                <td align="center" valign="top">
                    <?php echo $this->render('include/header.phtml'); ?>

                    <table cellspacing="0" cellpadding="20" border="0" width="650" style="background: #fff;margin-top:10px;" class="content">
                        <tr>
                            <td style="padding:0px;text-align:left;">
                                <h3 style="margin: 1px 0 4px;"><strong>
                                    <?php echo $this->translate('account')->__(
                                        'Hello, %s',
                                        $this->order->billing_firstname . ' ' . $this->order->billing_lastname
                                    )?>
                                </strong></h3>
                                <p style="margin: 1px 0 4px;"><?php echo $this->translate('sales')->__('Your order #%s status has been changed to %s', $this->order->number, $this->status) ?></p>
                                <?php if (!empty($this->comment)) : ?>
                                    <div class="comments">
                                        <?php echo $this->translate('account')->__('Comment') ?>:
                                        <?php echo $this->escape($this->comment) ?>
                                    </div>
                                <?php endif; ?>
                                <?php if ($this->order->customer_id) : ?>
                                    <p style="margin: 1px 0 4px;"><?php echo $this->translate('sales')->__('You can check the status of your order by <a %s>logging into your account</a>', 'href="' . $this->href('account/order', true, false) . '"'); ?></p>
                                <?php endif; ?>
                            </td>
                        </tr>
                    </table>

                    <?php echo $this->render('include/footer_html.phtml'); ?>
                </td>
            </tr>
        </table>
        </div>
    </body>
</html>
