<?php echo $this->translate('account')->__('Hello, %s', $this->order->billing_firstname . ' ' . $this->order->billing_lastname)?>


<?php echo $this->translate('sales')->__('Your order #%s status has been changed to %s', $this->order->number, $this->status) ?>

<?php if (!empty($this->comments)) : ?>
    <?php echo $this->translate('account')->__('Comment') ?>:
    <?php echo $this->escape($this->comment) ?>
<?php endif; ?>

<?php if ($this->order->customer_id) : ?>
<?php echo $this->translate('sales')->__('You can check the status of your order by logging into your account') ?>: <?php echo $this->href('account/order', true, false) ?>
<?php endif; ?>


<?php echo $this->render('include/footer_txt.phtml') ?>