<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=$CHARSET" />

<style type="text/css">
    a:link {color:#0066cc;}
    a:hover {background-color:#eeeecc; color:#0066cc;}
    a:visited {color:#0066cc;}
    a img {border:none;}
    .holder {background-color:#f9f9f9; border:1px solid #9a9a9a; font-size:9px; text-align:left; width:550px;}
    .header {font-size:10px; padding:0px; width:550px;}
    .content {font-size:10px; padding:5px; width:550px;}
    .content-line {padding:5px;}
    .footer {border-top:1px solid #9a9a9a; font-size:9px; margin-top:10px; text-align:center; width:550px;}
    .extra-info {background-color:#cccc99; border:1px solid #9a9a9a; font-size:10px; margin-top:10px; padding:5px; width:550px;}
    .extra-info-bold {font-weight:bold;}
    .disclaimer {background-color:#f9f9f9; border:1px solid #cccccc; font-size:10px; margin-top:10px; padding:5px; width:550px;}
    .disclaimer1 {color:#666666; padding:5px;}
    .disclaimer1 a:link {color:#666666;}
    .disclaimer1 a:visited {color:#666666;}
    .disclaimer2 {color:#666666; padding:5px;}
    .copyright {border-bottom:0px solid #9a9a9a; padding:5px;}
    body { color:#2f2f2f; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; padding: 0px; margin: 0px;}
    td { color:#2f2f2f; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif;}
    #logo img {border:none;}
</style>

</head>

<body>
    <div style="margin:0px; padding:0px; background-color:#ffffff; ">
    <table cellspacing="0" cellpadding="0" border="0" width="98%" style="margin:10px 0px; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; margin-bottom:10px;">
        <tr>
            <td align="center" valign="top">
                <table cellspacing="0" cellpadding="0" border="0" width="650" style="background: #fff; padding:0px;"  class="header">
                    <tr>
                        <td valign="top" id="logo">
                            <a href="<?php echo $this->href('/')?>"><?php echo $this->image('logo_mail.gif', 'style="border:none;"');?></a>
                        </td>
                        <td valign="top" align="right" style="padding-left: 0px">
                            <?php echo '   ' . $this->company['name']?>
                            <br/>
                            <?php echo  $this->company['email']?>
                            <br/>
                            <?php echo  $this->company['phone']?> 
                        </td>
                    </tr>
                </table>
            
                <table cellspacing="0" cellpadding="20" border="0" width="650" style="background: #fff;margin-top:10px; border: 1px solid #bbb" class="footer">
                    <tr>
                        <td class="content" style="padding:5px;text-align:left;">
                            <!-- Content Section -->
                            <strong>
                                <?php echo $this->translate('core')->__('Dear') . ', ';
                                if ($this->firstname && $this->lastname) {
                                    echo $this->firstname . ' ' . $this->lastname;
                                } else {
                                    echo 'customer';
                                }?>
                            </strong>
                            <br/>
                            <?php if ($this->reply)  :?>
                                <small><?php echo $this->translate('core')->__('This is reply on your letter to us') ?></small>
                                <br/>
                            <?php endif; ?>
                            <?php echo $this->translate('core')->__($this->text) ?>   
                            <!-- Content Section End-->
                        </td>
                    </tr>
                </table>
                
                <table cellspacing="0" cellpadding="20" border="0" width="650" style="background: #eee; border: 1px solid #bbb;margin-top:10px;" class="footer">
                    <tr>
                        <td class="copyright" style="padding:5px;">
                            <?php echo $this->translate('core')->__('Copyright')?> (c) <?php echo Axis_Date::now()->toString('Y'); ?> 
                            <a href=" <?php echo $this->href('/')?> " target="_blank"><?php echo $this->site ?></a>.
                            <?php echo $this->translate('core')->__("Powered by %s v. %s", "<a href='http://www.axiscommerce.com' title='Axis'>Axis</a>", Axis::app()->getVersion()) ?>
                        </td>
                    </tr>
                </table>
    
        
                <table cellspacing="0" cellpadding="20" border="0" width="650" style="margin-top:10px; padding:5px;background: #eee; border: 1px solid #bbb" class="disclaimer">
                    <tr>
                        <td class="disclaimer1" style="padding:5px;">
                            <?php 
                                echo $this->translate('core')->__('This email address was given to us by you or by one of our customers.');?><br/> <?php
                                echo $this->translate('core')->__('If you feel that you have received this email in error, please send an email to') . '  ' . $this->from 
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="disclaimer2" style="padding:5px;">
                            <?php 
                                echo $this->translate('core')->__('This email is sent in accordance with the US CAN-SPAM Law in effect 01/01/2004.');?><br/> <?php
                                echo $this->translate('core')->__('Removal requests can be sent to this address and will be honored and respected.');
                            ?>
                        </td>
                    </tr>
                </table>
        
            </td>
        </tr>
    </table>
    </div>  
</body>
</html>