<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <head>
        <?php $this->companyEmail = $this->company['support_email']; ?>
        <?php echo $this->render('include/html_head.phtml'); ?>
    </head>

    <body>
        <div style="margin:0px; padding:0px; background-color:#ffffff; ">
        <table cellspacing="0" cellpadding="0" border="0" width="98%" style="margin:10px 0px; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; margin-bottom:10px;">
            <tr>
                <td align="center" valign="top">
                    <?php echo $this->render('include/header.phtml'); ?>

                    <table cellspacing="0" cellpadding="20" border="0" width="650" style="background: #fff;margin-top:10px;" class="content">
                        <tr>
                            <td style="padding:0px;text-align:left;">
                                <h3 style="margin: 1px 0 4px;"><strong>
                                    <?php echo $this->translate('account')->__('Hello, %s', $this->escape($this->firstname . ' ' . $this->lastname)) ?>
                                </strong></h3>
                                <p style="margin: 1px 0 4px;"><?php echo $this->translate('account')->__('You have submitted a forgot password request.') ?></p>
                                <?php $link = '<a href="' . $this->link . '">' . $this->link . '</a>'; ?>
                                <p style="margin: 1px 0 4px;"><?php echo $this->translate('account')->__('If you want to change your password, follow this link: %s', $link) ?></p>
                                <p style="margin: 1px 0 4px;"><?php echo $this->translate('account')->__('This link is valid for only %d hours, until %s.', 24, Axis_Date::now()->addDay(1)->toString()) ?></p>
                            </td>
                        </tr>
                    </table>

                    <?php echo $this->render('include/footer_html.phtml'); ?>
                </td>
            </tr>
        </table>
        </div>
    </body>
</html>
