<?php echo $this->translate('account')->__('Hello, %s', $this->escape($this->firstname . ' ' . $this->lastname)) ?>


<?php echo $this->translate('account')->__('You have submitted a forgot password request.') ?>

<?php echo $this->translate('account')->__('If you want to change your password, follow this link: %s', $this->link) ?>

<?php echo $this->translate('account')->__('This link is valid for only %d hours, until %s.', 24, Axis_Date::now()->addDay(1)->toString()) ?>


<?php echo $this->render('include/footer_txt.phtml') ?>