<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <head>
        <?php echo $this->render('include/html_head.phtml'); ?>
        <style type="text/css">
        .table-order {margin-top: 10px;}
        .table-order td,
        .table-order th {width: 50%;}
        .order-header * {background-color:#7d7a7a;color:#fff;}
        .info-title * {background-color:#e8e8e8;}
        .no-border td {border:none;height:10px;}
        .table-products {margin-top: 10px;clear:both;}
        .table-products td,
        .table-products th {width: 25%;}
        .table-totals {margin-top:10px;clear:both;}
        .table-totals td {padding:2px;}
        </style>
    </head>

    <body>
        <div style="margin:0px; padding:0px; background-color:#ffffff; ">
        <table cellspacing="0" cellpadding="0" border="0" width="98%" style="margin:10px 0px; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; margin-bottom:10px;">
            <tr>
                <td align="center" valign="top">
                    <?php echo $this->render('include/header.phtml'); ?>

                    <table cellspacing="0" cellpadding="5" border="0" width="650" style="background: #fff;margin-top:10px;" class="content">
                        <tr>
                            <td style="padding:0px;text-align:left;">
                                <h3 style="margin: 1px 0 4px;"><strong>
                                    <?php $name = $this->escape(
                                        $this->order->getBilling()->getFirstname()
                                        . ' '
                                        . $this->order->getBilling()->getLastname()
                                    ) ?>
                                    <?php echo $this->translate('account')->__('Hello, %s', $name)?>
                                </strong></h3>
                                <p style="margin: 1px 0 4px;"><?php echo $this->translate('core')->__('Thank you for your order from %s', $this->site) ?></p>
                                <?php if ($this->order->customer_id): ?>
                                    <p style="margin: 1px 0 4px;"><?php echo $this->translate('sales')->__('You can check the status of your order by <a %s>logging into your account</a>', 'href="' . $this->href('account/order', true, false) . '" style="color:#1E7EC8;"'); ?></p>
                                <?php endif; ?>

                                <?php echo $this->render('sales/invoice_html.phtml'); ?>
                            </td>
                        </tr>
                    </table>

                    <?php echo $this->render('include/footer_html.phtml'); ?>
                </td>
            </tr>
        </table>
        </div>
    </body>
</html>