<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <head>
        <?php echo $this->render('include/html_head.phtml'); ?>
        <style type="text/css">
        .table-order {margin-top: 10px;}
        .table-order td,
        .table-order th {width: 50%;}
        .order-header * {background-color:#7d7a7a;color:#fff;}
        .info-title * {background-color:#e8e8e8;}
        .no-border td {border:none;height:10px;}
        .table-products {margin-top: 10px;clear:both;}
        .table-products td,
        .table-products th {width: 25%;}
        .table-totals {margin-top:10px;clear:both;}
        .table-totals td {padding:2px;}
        </style>
    </head>

    <body>
        <div style="margin:0px; padding:0px; background-color:#ffffff; ">
        <table cellspacing="0" cellpadding="0" border="0" width="98%" style="margin:10px 0px; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; margin-bottom:10px;">
            <tr>
                <td align="center" valign="top">
                    <?php echo $this->render('include/header.phtml'); ?>

                    <table cellspacing="0" cellpadding="20" border="0" width="650" style="background: #fff;margin-top:10px;" class="content">
                        <tr>
                            <td style="padding:0px;text-align:left;">
                                <p style="margin: 1px 0 4px;">
                                    <?php echo $this->translate('sales')->__('An order has been created on %s', $this->site) ?>
                                    <?php $route = Axis::config('core/backend/route') ?>
                                    <a href="<?php echo $this->href($route . '/sales_order/index/orderId/', true, false) . $this->order['id']?>" style="color:#1E7EC8;"><?php echo $this->translate('account')->__('View Order')?></a>
                                </p>
                                <?php echo $this->render('sales/invoice_html.phtml'); ?>
                            </td>
                        </tr>
                    </table>

                    <?php echo $this->render('include/copyright.phtml'); ?>
                </td>
            </tr>
        </table>
        </div>
    </body>
</html>