<?php $name = $this->escape(
    $this->order->getBilling()->getFirstname()
    . ' '
    . $this->order->getBilling()->getLastname()
) ?>
<?php echo $this->translate('account')->__('Hello, %s', $name)?>


<?php echo $this->translate('core')->__('Thank you for your order from %s', $this->site) ?>

<?php if ($this->order->customer_id): ?>
<?php echo $this->translate('sales')->__('You can check the status of your order by logging into your account') ?>: <?php echo $this->href('account/order', true, false) ?>
<?php endif; ?>


<?php echo $this->render('sales/invoice_txt.phtml') ?>


<?php echo $this->render('include/footer_txt.phtml') ?>