<?php echo $this->translate('sales')->__('An order has been created on %s', $this->site) ?>


<?php $route = Axis::config('core/backend/route') ?>
<?php echo $this->translate('account')->__('View Order') ?>: <?php echo $this->href($route . '/sales/order/index/orderId/', true, false) . $this->order['id']?>


<?php echo $this->render('sales/invoice_txt.phtml') ?>


<?php echo $this->render('include/footer_txt.phtml') ?>