<?php
$this->headScript()
    ->appendFile('/js/axis/admin/cms/comment/toolbar.js')
    ->appendFile('/js/axis/admin/cms/comment/tree.js')
    ->appendFile('/js/axis/admin/cms/comment/grid.js')
    ->appendFile('/js/axis/admin/cms/comment/window.js')
    ->appendFile('/js/axis/admin/cms/comment/panel.js');
?>

<script type="text/javascript">
<?php
$menu = '';
$statuses = '';
foreach ($this->status as $id => $name) :
    $name = addslashes($name);
    $statuses .= "[{$id}, '{$name}'], ";
    $menu .= "{
        text: '{$name}',
        cls: 'x-btn-text-icon',
        handler: function() {
            CommentGrid.setStatus({$id});
        }
    },\n";
endforeach;
echo 'var menuStatus = [' . substr($menu, 0, -2) . '];';
echo 'var status = [' . substr($statuses, 0, -2) . '];';
?>
</script>

