<ul id="filters">
<?php
$hurl       = Axis_HumanUri::getInstance();
$currency   = Axis::single('locale/currency')->getCurrency();
?>

<?php if ($hurl->hasParam('price')) : ?>
<li class="filter-box selected-filter">
    <a href="<?php echo $this->hurl(array('price' => null)); ?>"
    class="remove"
    title="<?php echo $this->translate('catalog')->__('Remove filter') ?>"><?php echo $this->translate('catalog')->__('Remove filter') ?></a>
    <span class="filter-name"><?php echo $this->translate('catalog')->__('Price')?>:</span> <?php
        $price = explode(',', $hurl->getParam('price'));
        echo $currency->toCurrency($price[0]) . ' &mdash; ';
        if (!empty($price[1])) {
            echo $currency->toCurrency($price[1]);
        } else {
            echo '&#8734;'; // infinity symbol
        }
    ?>
</li>
<?php endif; ?>

<?php if ($hurl->hasParam('manufacturer')) : ?>
<li class="filter-box selected-filter">
    <a href="<?php echo $this->hurl(array('manufacturer' => null)); ?>"
    class="remove"
    title="<?php echo $this->translate('catalog')->__('Remove filter') ?>"><?php echo $this->translate('catalog')->__('Remove filter') ?></a>
    <span class="filter-name"><?php echo $this->translate('catalog')->__('Manufacturer')?>:</span> <?php
        echo $hurl->getParam('manufacturer/title', $hurl->getParamSeo('manufacturer')); ?>
</li>
<?php endif; ?>

<?php if ($hurl->hasParam('attributes')) :
    foreach ($hurl->getParam('attributes') as $optionId => $item) : ?>
    <li class="filter-box selected-filter">
    <a href="<?php echo $this->hurl(array('attributes'=> array($optionId => null))); ?>"
    class="remove"
    title="<?php echo $this->translate('catalog')->__('Remove filter') ?>"><?php echo $this->translate('catalog')->__('Remove filter') ?></a>
    <span class="filter-name"><?php echo $item['option_name']?>:</span> <?php echo $item['value_name'];?>
    </li>
    <?php
    endforeach;
endif; ?>

<?php if ($this->box->hasData('filters/price/groups')) : ?>
<li class="filter-box" id="filter-price">
    <h3 class="filter-name"><?php echo $this->translate('catalog')->__('Price')?></h3>
    <ul>
<?php
$priceSubstract = $this->box->getData('filters/price/roundTo');
$priceMax       = isset($price[1]) ? $price[1] : null;
foreach ($this->box->getData('filters/price/groups') as $price) :
    $priceFrom  = $price['price_group'];
    $priceTo    = $price['price_group'] + $priceSubstract - 0.01;
    if ($priceMax && $priceTo > $priceMax) {
        $priceTo = $priceMax;
    }
    echo  '<li><a rel="nofollow" href="' . $this->hurl(array(
       'price' => $priceFrom . ',' . $priceTo,
       'page' => ''
    )) . '">'
        . $currency->toCurrency($priceFrom) . ' &mdash; ' . $currency->toCurrency($priceTo)
        . '</a> (' . $price['cnt'] . ')</li>';
endforeach; ?>
    </ul>
</li>
<?php endif; ?>

<?php if ($this->box->hasData('filters/manufacturer')) : ?>
<li class="filter-box" id="filter-manufacturer">
    <h3 class="filter-name"><?php echo $this->translate('catalog')->__('Manufacturer')?></h3>
    <ul>
<?php
foreach ($this->box->getData('filters/manufacturer') as $item) :
    echo  '<li><a rel="nofollow" href="' . $this->hurl(array(
           'manufacturer' => array(
              'value' => $item['manufacturer_id'],
              'seo' => $item['manufacturer_url']
           ), 'page' => ''))
        . '">'
        . $this->escape($item['manufacturer_title'])
        . '</a> (' . $item['cnt'] . ')</li>';
endforeach; ?>
    </ul>
</li>
<?php endif; ?>

<?php if ($this->box->hasData('filters/attributes')) :
echo '<li class="filter-box" id="filter-attributes">';
    foreach ($this->box->getData('filters/attributes') as $optionId => $values) :
        echo '<h3 class="filter-name">' . $values[0]['option_name'] . '</h3><ul>';
        foreach ($values as $value) :
            echo '<li><a rel="nofollow" href="' . $this->hurl(array(
                'attributes' => array(
                    "$optionId" => array(
                       'value' => $value['option_value_id'],
                       'seo' => $value['option_name'] . '=' . $value['value_name']
                    )
                ),
                'page' => ''
            )) . '">' . $value['value_name'] . '</a> (' . $value['cnt'] . ')</li>';
        endforeach;
        echo '</ul>';
    endforeach;
echo '</li>';
endif; ?>
</ul>