<ul class="navigation">
    <li class="level0 nav-home">
        <a href="<?php echo $this->href('/') ?>" title="<?php echo $this->translate('core')->__('Home') ?>"
            ><span><?php
                echo $this->translate('core')->__('Home')
            ?></span
        ></a>
    </li>
    <?php echo $this->navigation()->menu($this->box->menu)->disableWrapper(); ?>
    <?php echo $this->box('cms/block')->setStaticBlock('menu');?>
</ul>
