<?php
    $menu = $this->box->menu;
    $menu->addPage(array(
        'label' => $this->translate('core')->__('Home'),
        'title' => $this->translate('core')->__('Home'),
        'uri'   => $this->href('/'),
        'order' => 0,
        'class' => 'nav-home'
    ));
    ?>
<ul class="navigation">
    <?php echo $this->navigation()->menu($menu)->disableWrapper(); ?>
    <?php echo $this->box('cms/block')->setStaticBlock('menu');?>
</ul>
