<?php

echo $this->message();

if (count($this->addressList)) :
    $addressArray = array(
        0 => 'New Address'
    );
    foreach ($this->addressList as $address) :
        $addressArray[$address->id] = trim($this->address($address, ', '), ', ');
    endforeach;

    echo $this->formSelect(
        $this->escape($this->addressType) . '-id',
        $this->selectedAddressId,
        array(
            'onchange' => 'Address.onChange(this)'
        ),
        $addressArray
    );
endif; ?>
