<?php echo $this->message() ?>

<div class="col3-set">
    <div class="billing-address address col-1">
        <div class="head">
            <h4 class="address-title">
                <?php echo $this->translate('checkout')->__('Billing Address');?>
            </h4>
        </div>
        <address><?php echo $this->address($this->checkout['billing']); ?></address>
        <div class="foot">
            <h5><?php echo $this->translate('checkout')->__('Payment Method'); ?>:</h5>
            <p><?php echo $this->checkout['payment']; ?></p>
            <?php echo $this->paymentForm($this->checkout['payment_code'], 'confirm')?>
        </div>
    </div>

    <div class="shipping-address address col-2">
        <div class="head">
            <h4 class="address-title">
                <?php echo $this->translate('checkout')->__('Delivery Address'); ?>
            </h4>
        </div>
        <address><?php echo $this->address($this->checkout['delivery']); ?></address>
        <div class="foot">
            <h5><?php echo $this->translate('checkout')->__('Shipping Method');?>:</h5>
            <p><?php echo $this->checkout['shipping']; ?></p>
            <?php echo $this->shippingForm($this->checkout['shipping_code'], 'confirm')?>
        </div>
    </div>
</div>

<table id="shopping-cart-table" class="data-table">
<thead>
<tr>
    <th><?php echo $this->translate('checkout')->__('Product')?></th>
    <th><?php echo $this->translate('checkout')->__('Price')?></th>
    <th><?php echo $this->translate('checkout')->__('Quantity')?></th>
    <th><?php echo $this->translate('checkout')->__('Final price')?></th>
</tr>
</thead>
<tfoot>
<tr>
    <td colspan="100" class="a-right">
        <form method="post" action="<?php echo $this->href('/checkout/onepage/process', true)?>" id="form-checkout">
            <p class="order-comment-row">
                <label for="comment"><?php echo Axis::translate('checkout')->__('You can add some additional information for our manager')?>:</label><br/>
                <textarea rows="5" cols="80" class="input-text order-comment" name="comment" id="comment"></textarea>
            </p>
            <?php echo $this->button($this->translate('checkout')->__('Create Order'), array(
                'class' => 'button btn-confirm',
                'type' => 'submit'
            ), 'button') ?>
        </form>
    </td>
</tr>
</tfoot>

<?php foreach ($this->checkout['products'] as $itemId => &$product) : ?>
<tr valign="top">
    <td>
        <?php echo $product['name'];?><br />
        <?php foreach ($product['attributes'] as $attr) { ?>
            <div><small><?php
                echo $attr['product_option'] . ': ' . $this->escape($attr['product_option_value']);
            ?> </small></div>
        <?php } ?>
    </td>
    <td><?php echo $this->currency($product['final_price']);?></td>
    <td class="a-center"><?php echo $product['quantity'] ?></td>
    <td><?php echo $this->currency($product['quantity'] * $product['final_price']);?></td>
</tr>
<?php endforeach; ?>

<?php foreach ($this->checkout['totals'] as $total) : ?>
<tr>
    <td colspan="3" class="a-right"><?php echo $this->translate('checkout')->__($total['title']) ?>:&nbsp;</td>
    <td ><?php echo $this->currency($total['total'])?></td>
</tr>
<?php endforeach; ?>

<tr>
    <td colspan="3" class="a-right"><?php echo $this->translate('checkout')->__('Total')?>:&nbsp;</td>
    <td><?php echo $this->currency($this->checkout['total'])?></td>
</tr>
</table>

<script type="text/javascript">
    decorateTable('shopping-cart-table');
</script>