<h4><?php echo $this->translate('checkout')->__("Login")?></h4>
<form method="post" id="form-login" class="form-login" action="<?php
    echo $this->href('/account/auth/login', true) ?>">
    <p>
        <strong><?php echo $this->translate('checkout')->__("Already registered?")?></strong>
    </p>
    <dl class="form">
        <dt><label for="username"><?php echo $this->translate('checkout')->__('Email')?></label>
            <span class="required">*</span>
        </dt>
        <dd><input type="text" id="username" name="username"
            class="input-text required email"
            /></dd>
        <dt><label for="password"><?php echo $this->translate('checkout')->__('Password')?></label>
            <span class="required">*</span>
        </dt>
        <dd><input type="password" id="password" name="password"
            class="input-text required"
            /></dd>
    </dl>
    <script type="text/javascript">
        $("#form-login").validate();
    </script>
    <div class="button-set">
        <?php echo $this->button($this->translate('checkout')->__('Login'), array(
            'class' => 'button btn-login',
            'type' => 'submit'
        ), 'button') ?>
    </div>
</form>