 <form method="post" id="form-guest" class="form-login" action="<?php
    echo $this->href('/checkout/onepage/as-guest', true) ?>">
    <h4><?php echo $this->translate('checkout')->__("Checkout as a Guest or Register");?></h4>
    <ul class="form-list">
        <li>
            <input id="not_register_guest" type="radio" value="0" name="register_guest"/>
            <label for="not_register_guest">
                <?php echo $this->translate('checkout')->__("Checkout as Guest");?>
            </label>
        </li>
        <li>
            <input id="register_guest" type="radio" checked="checked" value="1" name="register_guest"/>
            <label for="register_guest">
                <?php echo $this->translate('checkout')->__("Register");?>
            </label>
        </li>
    </ul>
    <strong><?php echo $this->translate('checkout')->__("Register and save time!");?></strong>
    <br/>
    <?php echo $this->translate('checkout')->__("Register with us for future convenience")?>:
    <ul class="disc">
        <li><?php echo $this->translate('checkout')->__("Fast and easy check out");?></li>
        <li><?php echo $this->translate('checkout')->__("Easy access to your order history and status");?></li>
    </ul>
    <div class="block-button-continue">
        <div class="loading-bar">
            <span><?php echo $this->translate('checkout')->__('loading...')?></span>
        </div>
        <?php echo $this->button($this->translate('checkout')->__('Continue'), array(
            'class' => 'button btn-continue',
            'type' => 'button',
            'onclick' => 'Customer.asGuest();'
        ), 'button') ?>
    </div>
</form>