<?php
    $_box = $this->box;
    $productId = $_box->product_id;
//    $reviewCount = $_box->review_count[$productId];
    if (isset($_box->review_count[$productId])
        && $reviewCount = $_box->review_count[$productId]) : ?>
    <p class="review-view">
        <a href="<?php echo $this->href('review/product/' . $_box->product_url) ?>"
            title="<?php echo $this->translate('community')->__("View all user reviews (%d)", $reviewCount)?>">
            <?php echo $this->translate('community')->__("View all user reviews (%d)", $reviewCount)?>
        </a></p>
    <?php if (isset($_box->ratings[$productId])) : ?>
        <?php echo $this->ratings(
            $_box->ratings[$productId],
            $this->href('review/product/' . $_box->product_url),
            $_box->hasData('small_stars') && $_box->getData('small_stars')
        ) ?>
    <?php endif; ?>
<?php else: ?>
    <p class="review-add">
        <a href="<?php echo $this->href('review/add/product/' . $productId) ?>"
            rel="nofollow">
            <?php echo $this->translate('community')->__('Be the first to review this product') ?>
        </a></p>
<?php endif; ?>