<?php echo $this->title($this->pageTitle) ?>
<?php if (count($this->review)): $review = $this->review; ?>
<div class="review-detail">
<?php
$product = $review['product'];
$productUrl = $this->hurl(array(
    'product' => array('value' => $product['id'], 'seo' => $product['key_word']),
    'controller' => 'catalog',
    'action' => 'product'
), false, true);
$imagePath = isset($product['images'][$product['image_listing']]) ?
    $product['images'][$product['image_listing']]['path'] : '';
$imageTitle = isset($product['images'][$product['image_listing']]) ?
    $product['images'][$product['image_listing']]['title'] : '';

if (empty($review['customer_id'])):
    $author = empty($review['author']) ? 'Guest' : $review['author'];
else:
    $authorUrl = $this->href("review/customer/id/{$review['customer_id']}");
    $authorTitle = $this->translate('community')->__("View all reviews written by %s", $review['author']);
    $author = "<a href='" . $authorUrl . "' title='" . $authorTitle . "' class='review-author'>{$review['author']}</a>";
endif;

?>
<div class="review">
    <div class="product-image">
        <a href="<?php echo $productUrl;?>"
            title="<?php echo $this->escape($imageTitle) ?>"
        ><?php
            echo $this->imager('/product' . $imagePath, array(
                'width'     => $this->config()->image->product->widthSmall,
                'height'    => $this->config()->image->product->heightSmall,
                'alt'       => $this->escape($product['name']),
                'title'     => $this->escape($imageTitle),
                'seo'       => $product['image_seo_name']
            ));
        ?></a>
        <?php if (isset($this->average_ratings[$product['id']])): ?>
            <?php echo $this->ratings($this->average_ratings[$product['id']], $this->href("review/product/{$product['key_word']}")) ?>
        <?php endif ?>
        <?php echo $this->price($product['prices']) ?>
    </div>
    <div class="review-info">
        <a href="<?php echo $productUrl ?>"
            class="product-name"
            title="<?php echo $this->translate('community')->__("Read about %s", $product['name']) ?>"
        ><?php echo $product['name'] ?></a>
        <a href="<?php echo $this->href("review/product/{$product['key_word']}") ?>"
            title="<?php echo $this->translate('community')->__("View all reviews for %s", $product['name']) ?>"
        ><small><?php echo $this->translate('community')->__("View all reviews") ?></small></a>
        <span class="review-date"><small><?php echo $this->translate('community')->__("Reviewed on %s by %s", $review['date_created'], $author) ?></small></span>
        <h5 class="review-title"><?php echo $review['title'] ?></h5>
        <?php if (isset($review['ratings'])): ?>
            <?php echo $this->ratings($review['ratings'], '#') ?>
        <?php endif ?>
        <p class="review-pros"><strong><?php echo $this->translate('community')->__("Pros") . ': ' ?></strong><?php echo nl2br($this->escape($review['pros'])) ?></p>
        <p class="review-cons"><strong><?php echo $this->translate('community')->__("Cons") . ': ' ?></strong><?php echo nl2br($this->escape($review['cons'])) ?></p>
        <p class="review-summary"><strong><?php echo $this->translate('community')->__("Summary") . ': ' ?></strong><?php echo nl2br($this->escape($review['summary'])) ?></p>
    </div>
</div>
</div>
<?php
else:
    echo $this->translate('community')->__("Review not found");
endif;