<?php echo $this->title($this->pageTitle) ?>

<?php if (!$this->productId) :
    echo $this->translate('catalog')->__('Product not found');
    return;
    endif;?>

<?php if (count($this->data['reviews'])):
$review = current($this->data['reviews']);
$product = $review['product'];
$productUrl = $this->hurl(array(
    'product' => array('value' => $product['id'], 'seo' => $product['key_word']),
    'controller' => 'catalog',
    'action' => 'product'
), false, true);
$imagePath = isset($product['images'][$product['image_listing']]) ?
    $product['images'][$product['image_listing']]['path'] : '';
$imageTitle = isset($product['images'][$product['image_listing']]) ?
    $product['images'][$product['image_listing']]['title'] : '';
?>

<div class="review-product-average">
    <div class="head">
        <h2><a href="<?php echo $productUrl ?>"
            class="product-name"
            title="<?php echo $this->translate('community')->__("Read about %s", $product['name']) ?>"
        ><?php echo $product['name'] ?></a></h2>
    </div>
    <div class="content">
        <div class="product-image">
            <a href="<?php echo $productUrl;?>"
                title="<?php echo $this->escape($imageTitle) ?>"
            ><?php
                echo $this->imager('/product' . $imagePath, array(
                    'width'     => $this->config()->image->product->widthSmall,
                    'height'    => $this->config()->image->product->heightSmall,
                    'alt'       => $this->escape($product['name']),
                    'title'     => $this->escape($imageTitle),
                    'seo'       => $product['image_seo_name']
                ));
            ?></a>
        </div>
        <div class="product-info">
            <?php if (isset($this->average_ratings[$this->productId])): ?>
                <?php echo $this->ratings($this->average_ratings[$this->productId], '#', false) ?>
            <?php else: ?>
                <?php echo $this->translate('community')->__('No ratings are available') ?>
            <?php endif; ?>
        </div>
        <div class="product-common">
            <?php echo $this->price($product['prices']) ?>
            <?php if (Axis::model('community/review')->canAdd()) : ?>
                <a href="#form-review"
                    rel="nofollow"
                    title="<?php echo $this->translate('community')->__("Write review for %s", $product['name']) ?>"
                ><span><?php echo $this->translate('community')->__("Write review") ?></span></a>
            <?php else: ?>
                <a href="<?php echo $this->href('review/login') ?>"
                    rel="nofollow"
                    title="<?php echo $this->translate('community')->__("Log in to write a review") ?>"
                ><span><?php echo $this->translate('community')->__("Log in to write a review") ?></span></a>
            <?php endif ?>
        </div>
    </div>
</div>

<?php echo $this->render('review/list/toolbar.phtml') ?>
<ol class="review-product-list">
<?php foreach ($this->data['reviews'] as $review) :
$authorName = $this->escape($review['author']);
if (empty($review['customer_id'])):
    $author = empty($review['author']) ? 'Guest' : $authorName;
else:
    $authorUrl = $this->href("review/customer/id/{$review['customer_id']}");
    $authorTitle = $this->translate('community')->__("View all reviews written by %s", $authorName);
    $author = "<a href='" . $authorUrl . "' title='" . $authorTitle . "' class='review-author'>{$authorName}</a>";
endif;

?>
<li class="review" id="review_<?php echo $review['id'] ?>">
    <div class="review-info">
        <h5 class="review-title"><a href="<?php echo $this->href("review/detail/id/{$review['id']}") ?>"
            title="<?php echo $this->translate('community')->__("Read review") ?>"><?php echo $review['title'] ?></a></h5>
        <span class="review-date"><small><?php echo $this->translate('community')->__("Reviewed on %s by %s", $review['date_created'], $author) ?></small></span>
        <p class="review-pros"><strong><?php echo $this->translate('community')->__("Pros") ?>: </strong><?php echo nl2br($this->escape($review['pros'])) ?></p>
        <p class="review-cons"><strong><?php echo $this->translate('community')->__("Cons") ?>: </strong><?php echo nl2br($this->escape($review['cons'])) ?></p>
        <p class="review-summary"><strong><?php echo $this->translate('community')->__("Summary") ?>: </strong><?php echo nl2br($this->escape($review['summary'])) ?></p>
    </div>
    <?php if (isset($review['ratings'])): ?>
        <?php echo $this->ratings($review['ratings'], $this->href("review/detail/id/{$review['id']}"), false) ?>
    <?php endif ?>
</li>
<?php endforeach; ?>
</ol>
<?php echo $this->render('review/list/toolbar.phtml') ?>
<?php else:
    echo $this->translate('community')->__('There are no reviews for this product yet');
endif;?>

<div class="review-write">
    <div class="head"><h4 class="title"><?php echo $this->translate('community')->__("Write your review") ?></h4></div>
    <div class="content">
        <?php $this->headScript()->appendFile('/js/axis/community/ratings.js') ?>
        <?php echo $this->formReview->render($this) ?>
        <?php if (!Axis::single('community/review')->canAdd()) : ?>
        <a href="<?php echo $this->href('review/login') ?>"
            rel="nofollow"
            title="<?php echo $this->translate('community')->__("Log in to write a review") ?>"
        ><span><?php echo $this->translate('community')->__("Log in to write a review") ?></span></a>
        <?php endif ?>
        <script type="text/javascript">
            $("#form-review").validate();
            $('#form-review .review-rating').ratings();
        </script>
    </div>
</div>