<?php echo $this->title($this->pageTitle) ?>
<?php if (count($this->data['reviews'])):?>
<?php echo $this->render('community/review/list/toolbar.phtml') ?>
<form id="form-compare" method="post" action="<?php echo $this->href($this->catalogUrl . '/product-compare/compare') ?>">
<ol class="review-list">
<?php foreach ($this->data['reviews'] as $review) :
    $product = $review['product'];
    $productUrl = $this->hurl(array(
        'product' => array('value' => $product['id'], 'seo' => $product['key_word']),
        'controller' => 'catalog',
        'action' => 'product'
    ), false, true);
    $imagePath = isset($product['images'][$product['image_listing']]) ?
        $product['images'][$product['image_listing']]['path'] : '';
    $imageTitle = isset($product['images'][$product['image_listing']]) ?
        $product['images'][$product['image_listing']]['title'] : '';

    $authorName = $this->escape($review['author']);
    if (empty($review['customer_id'])):
        $author = empty($review['author']) ? 'Guest' : $authorName;
    else:
        $authorUrl = $this->href("review/customer/id/{$review['customer_id']}");
        $authorTitle = $this->translate('community')->__("View all reviews written by %s", $authorName);
        $author = "<a href='" . $authorUrl . "' title='" . $authorTitle . "' class='review-author'>{$authorName}</a>";
    endif;

    ?>
    <li class="review">
        <div class="product-image">
            <a href="<?php echo $productUrl;?>"
                title="<?php echo $this->escape($imageTitle) ?>"
            ><?php
                echo $this->imager('/product' . $imagePath, array(
                    'width'  => $this->config()->image->product->widthSmall,
                    'height' => $this->config()->image->product->heightSmall,
                    'alt' => $this->escape($product['name']),
                    'title' => $this->escape($imageTitle),
                    'seo' => $product['image_seo_name']
                ));
            ?></a>
            <?php if (isset($this->average_ratings[$product['id']])): ?>
                <?php echo $this->ratings(
                    $this->average_ratings[$product['id']],
                    $this->href("review/product/{$product['key_word']}")
                ) ?>
            <?php endif ?>
        </div>
        <div class="product-compare">
            <input type="checkbox" name="product_id[]"
                value="<?php echo $product['id'] ?>"
                title="<?php echo $this->translate('community')->__('Select to compare') ?>"/>
        </div>
        <div class="product-common">
            <?php echo $this->price($product['prices']) ?>
            <?php if (Axis::model('community/review')->canAdd()) : ?>
            <a href="<?php echo $this->href("review/product/{$product['key_word']}#form-review") ?>"
                rel="nofollow"
                title="<?php echo $this->translate('community')->__("Write review for %s", $product['name']) ?>"
            ><span><?php echo $this->translate('community')->__("Write review") ?></span></a>
            <?php else: ?>
            <a href="<?php echo $this->href('review/login') ?>"
                rel="nofollow"
                title="<?php echo $this->translate('community')->__("Log in to write a review") ?>"
            ><span><?php echo $this->translate('community')->__("Log in to write a review") ?></span></a>
            <?php endif ?>
        </div>
        <div class="review-info">
            <a href="<?php echo $productUrl ?>"
                class="product-name"
                title="<?php echo $this->translate('community')->__("Read about %s", $product['name']) ?>"
            ><?php echo $product['name'] ?></a>
            <a href="<?php echo $this->href("review/product/{$product['key_word']}") ?>"
                title="<?php echo $this->translate('community')->__("View all reviews for %s", $product['name']) ?>"
            ><small><?php echo $this->translate('community')->__("View all reviews") ?></small></a>
            <span class="review-date"><small><?php echo $this->translate('community')->__("Reviewed on %s by %s", $review['date_created'], $author) ?></small></span>
            <h5 class="review-title"><a href="<?php echo $this->href("review/detail/id/{$review['id']}") ?>"
                title="<?php echo $this->translate('community')->__('Read review') ?>"
                ><?php echo $this->escape($review['title']) ?></a></h5>
            <?php if (isset($review['ratings'])): ?>
                <?php echo $this->ratings($review['ratings'], $this->href("review/detail/id/{$review['id']}")) ?>
            <?php endif ?>
            <p class="review-pros"><strong><?php echo $this->translate('community')->__("Pros") . ': ' ?></strong><?php echo nl2br($this->escape($review['pros'])) ?></p>
            <p class="review-cons"><strong><?php echo $this->translate('community')->__("Cons") . ': ' ?></strong><?php echo nl2br($this->escape($review['cons'])) ?></p>
            <p class="review-summary"><strong><?php echo $this->translate('community')->__("Summary") . ': ' ?></strong><?php echo nl2br($this->escape($review['summary'])) ?></p>
        </div>
    </li>
<?php endforeach; ?>
</ol>
</form>
<?php echo $this->render('community/review/list/toolbar.phtml') ?>
<?php else:
    echo $this->translate('community')->__("Review not found");
endif;?>