<?php 
$categories = $this->box->getData('categories', array());
$pages = $this->box->getData('pages', array());
?>
<div class="box base-mini box-cms-navigation">
    <div class="head">
        <span class="title">
            <?php if (count($categories)) : ?>
                <a href="<?php echo $this->href('pages') ?>">
                    <?php echo $this->translate('cms')->__($this->box->title);?>
                </a>
            <?php else : ?>
                <?php echo $this->translate('cms')->__($this->box->title);?>
            <?php endif; ?>
        </span>
    </div>
    <div class="content">
        <ul class="cms-page-list no-bullet no-indent">
            <?php foreach ($categories as $_category) : ?>
            <li class="icon-folder">
                <a href="<?php echo $this->url(array(
                    'cat' => $_category['link']),
                    'cms_category', true); ?>"
                ><?php echo empty($_category['title'])
                    ? $_category['link'] : $_category['title']; ?>
                </a>
            </li>
            <?php endforeach; ?>
            <?php foreach ($pages as $_page) : ?>
            <li class="icon-page">
                <a href="<?php echo $this->url(array(                                    
                    'page' => $_page['link']
                    ), 'cms_page', true); ?>"
                ><?php echo ($_page['title'] == '' ? $_page['link'] : $_page['title']); ?>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>