<?php echo $this->message() ?>

<table id="shopping-cart-table" class="data-table">
    <thead>
        <tr>
            <th><?php echo $this->translate('catalog')->__('Product')?></th>
            <th><?php echo $this->translate('catalog')->__('Price')?></th>
            <th><?php echo $this->translate('catalog')->__('Quantity')?></th>
            <th><?php echo $this->translate('checkout')->__('Final price')?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->checkout['products'] as $itemId => $product) : ?>
            <tr valign="top">
                <td>
                    <?php echo $product['name']; ?>
                    <?php foreach ($product['attributes'] as $attr) : ?>
                        <div><small><?php
                            echo $attr['product_option'] . ': '
                                . $this->escape($attr['product_option_value']);
                        ?></small></div>
                    <?php endforeach ?>
                </td>
                <td><?php echo $this->currency($product['final_price']); ?></td>
                <td class="a-center"><?php
                    echo $product['decimal'] ?
                        $product['quantity'] : (int)$product['quantity'];
                ?></td>
                <td><?php echo $this->currency($product['quantity'] * $product['final_price']); ?></td>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->checkout['totals'] as $total) : ?>
            <tr>
                <td colspan="3" class="a-right"><?php
                    echo $this->translate('checkout')->__($total['title']);
                ?></td>
                <td><?php echo $this->currency($total['total'])?></td>
            </tr>
        <?php endforeach; ?>

        <tr class="grand-total">
            <td colspan="3" class="a-right label"><?php
                echo $this->translate('checkout')->__('Total');
            ?></td>
            <td><?php echo $this->currency($this->checkout['total']); ?></td>
        </tr>
    </tbody>
</table>

<script type="text/javascript">
    decorateTable('shopping-cart-table');
</script>
