<?php echo $this->message() ?>

<table id="shopping-cart-table" class="data-table">
    <colgroup>
        <col class="col-product-name"/>
        <col class="col-product-price"/>
        <col class="col-product-qty"/>
        <col class="col-product-final-price"/>
    </colgroup>
    <thead>
        <tr>
            <th><?php echo $this->translate('catalog')->__('Product')?></th>
            <th><?php echo $this->translate('catalog')->__('Price')?></th>
            <th><?php echo $this->translate('catalog')->__('Quantity')?></th>
            <th><?php echo $this->translate('checkout')->__('Final price')?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->checkout['products'] as $itemId => $product) : ?>
            <tr valign="top">
                <td>
                    <?php echo $product['name']; ?>
                    <?php foreach ($product['attributes'] as $attr) : ?>
                        <div><small><?php
                            echo $attr['product_option'] . ': '
                                . $this->escape($attr['product_option_value']);
                        ?></small></div>
                    <?php endforeach ?>
                </td>
                <td><?php echo $this->currency($product['final_price']); ?></td>
                <td class="a-center">
                    <div class="qty-spinner">
                        <?php
                            echo $this->formText(
                                "quantity[$itemId]",
                                $product['decimal'] ? $product['quantity'] : (int)$product['quantity'],
                                array(
                                    'size'  => '2',
                                    'class' => 'input-text input-qty number required'
                                )
                            );
                        ?>
                        <button type="button" class="spinner remove">-</button>
                        <button type="button" class="spinner add">+</button>
                    </div>
                </td>
                <td><?php echo $this->currency($product['quantity'] * $product['final_price']); ?></td>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->checkout['totals'] as $total) : ?>
            <tr>
                <td colspan="3" class="a-right"><?php
                    echo $this->translate('checkout')->__($total['title']);
                ?></td>
                <td><?php echo $this->currency($total['total'])?></td>
            </tr>
        <?php endforeach; ?>

        <tr class="grand-total">
            <td colspan="3" class="a-right label"><?php
                echo $this->translate('checkout')->__('Total');
            ?></td>
            <td><?php echo $this->currency($this->checkout['total']); ?></td>
        </tr>
    </tbody>
</table>

<script type="text/javascript">
    decorateTable('shopping-cart-table');
</script>
