<?php $this->headScript()->appendFile('/js/axis/admin/roles.js'); ?>

<div id="parent-role-tpl" class="x-hidden">
    <input id="role-{id}" type="checkbox" value="{id}" name="role[]"/>
    <label for="role-{id}">{name}</label><br />
</div>

<table id="role-info-table" width="100%" style="padding: 10px;">
<tr valign="top">
    <td>
        <div>
            <dl>
                <dt><?php echo $this->translate('admin')->__('Name')?>:</dt>
                <dd><?php echo $this->formText('roleName', $this->roleName);?></dd>

                <dt><?php echo $this->translate('admin')->__('Parent Roles')?>:</dt>
                <dd><div id="parent-roles"></div></dd>
            </dl>
        </div>
    </td>

    <td>
        <?php echo $this->translate('admin')->__('Rules (Allow|Deny)')?>:<br />
        <div id="role-rules"><?php echo $this->resourcesTree($this->resources) ?></div>
    </td>
</tr>
</table>
