<script type="text/javascript">
    function removeRate(id) {
        $('#wraper-' + id).remove();
    }
    function addRate() {
        var rand = Math.floor(Math.random() * 2147483647);
        var template = $('#shippingmultirate-template').html();
        template = template.replace(/{template_id}/g, rand)
            .replace(/{template}/g, 'value[' + rand + ']');
        $('#shippingmultirate-template').before(template);
    }
</script>
<?php 
$value = $this->value;
$i = 1;
$_subcode = $_title = $_price = $_minOrderTotal = $_maxOrderTotal = '';
foreach ($value as $subcode => $item) :
    $_title = $item['title'];
    $_price = $item['price'];
    $_minOrderTotal = isset($item['minOrderTotal']) ? $item['minOrderTotal'] : '';
    $_maxOrderTotal = isset($item['maxOrderTotal']) ? $item['maxOrderTotal'] : '';
?>
<div id="wraper-<?php echo $i;?>">
    Subcode      : <?php echo $this->formText('value[' . $i . '][subcode]', $subcode, array('size' => '10'));?>
    Title        : <?php echo $this->formText('value[' . $i . '][title]', $_title, array('size' => '10'))?> 
    Price        : <?php echo $this->formText('value[' . $i . '][price]', $_price, array('size' => '10'))?>
    Min Subtotal : <?php echo $this->formText('value[' . $i . '][minOrderTotal]', $_minOrderTotal, array('size' => '10'))?>
    Max Subtotal : <?php echo $this->formText('value[' . $i . '][maxOrderTotal]', $_maxOrderTotal, array('size' => '10'))?>
    <?php echo $this->formButton('shippingmultirate-template-remove', 'Remove', array('onclick' => 'removeRate(' . $i . ');'))?>
</div>
<?php 
$i++;
endforeach; ?>
<div id="shippingmultirate-template" style="display:none" >
    <div id="wraper-{template_id}">
        Subcode      : <?php echo $this->formText('{template}[subcode]', $_subcode, array('size' => '10'));?>
        Title        : <?php echo $this->formText('{template}[title]', $_title, array('size' => '10'))?> 
        Price        : <?php echo $this->formText('{template}[price]', $_price, array('size' => '10'))?>
        Min Subtotal : <?php echo $this->formText('{template}[minOrderTotal]', $_minOrderTotal, array('size' => '10'))?>
        Max Subtotal : <?php echo $this->formText('{template}[maxOrderTotal]', $_maxOrderTotal, array('size' => '10'))?>
        <?php echo $this->formButton('shippingmultirate-template-remove', 'Remove', array('onclick' => 'removeRate({template_id});'))?>
    </div>
</div>
<?php echo $this->formButton('shippingmultirate-template-add', 'Add', array('onclick' => 'addRate();'));?>