<?php
$this->headScript()
    ->appendFile('js/ckeditor/ckeditor.js')
    ->appendFile('js/axis/admin/core/ckeditor.js')
    ->appendFile('js/ext-axis/src/widgets/form/CKEditor.js');

$this->headScript()
    ->appendFile('js/axis/admin/cms/index/category.js')
    ->appendFile('js/axis/admin/cms/index/category/tree.js')
    ->appendFile('js/axis/admin/cms/index/category/window.js')
    ->appendFile('js/axis/admin/cms/index/toolbar.js')
    ->appendFile('js/axis/admin/cms/index/page.js')
    ->appendFile('js/axis/admin/cms/index/page/grid.js')
    ->appendFile('js/axis/admin/cms/index/page/tabs/description.js')
    ->appendFile('js/axis/admin/cms/index/page/tabs/seo.js')
    ->appendFile('js/axis/admin/cms/index/page/tabs/category.js')
    ->appendFile('js/axis/admin/cms/index/page/window.js')
    ->appendFile('js/axis/admin/cms/index/panel.js');
?>

<script type="text/javascript">
    //batch menu
    var layoutMenu = [
    <?php
        $menu = "";
        foreach (Axis_Collect_Layout::collect() as $name => $value) {
            $value = addslashes($value);
            $menu .= "{
                text: '$value',
                handler: function() {
                    PageGrid.batchProcess('layout', '$name');
                }
            },\n";
        }
        echo substr($menu, 0, -2);
    ?>];
</script>