<div class="payment-additional" style="display:none;">
    <dl class="form" id="extra-fields-<?php echo $this->payment->getCode();?>">
        <dt><?php echo$this->translate('PaymentCheckMoney')->__("Make Check payable to")?>:</dt>
        <dd><?php echo $this->payment->config('sendCheckTo') ?></dd>
        <dt><?php echo$this->translate('PaymentCheckMoney')->__("Send Check to")?>:</dt>
        <dd><?php echo $this->payment->config('payTo') ?></dd>
    </dl>
</div>