<?php 
//plugins
$this->headScript()->appendFile('/js/ext-ux/grid/GridSearch.js');

//gui
$this->headScript()->appendFile('/js/axis/admin/customer/wishlist.js');

$this->setButtons(array(array(
    'title' => Axis::translate('Axis_Admin')->__('Back'),
    'onclick' => 'history.back()',
    'class' => 'alt-button'
)))
?>
<script type="text/javascript">

<?php if ($this->wishlistId) : ?>
    var wishlistId = <?php echo $this->wishlistId?>;
<?php endif; ?>

var gridWishlist;

</script>