<?php echo $this->title($this->pageTitle) ?>

<form class="axis-form" method="post" action="<?php echo $this->href('/checkout/wizard/set-' . $this->addressType, true);?>">
<div id="<?php echo $this->escape($this->addressType); ?>-radios">
<?php
if (count($this->addressList)) : ?>
<table class="table">
<?php
$i = 0;
$columnCount = 3;
foreach ($this->addressList as $address) : ?>

    <?php if ($i % $columnCount == 0): ?>
        <tr>
    <?php endif; ?>

    <td>
        <div class="address">
            <h5 class="address-title label-inline">
                <input type="radio" name="<?php echo $this->escape($this->addressType) ?>-id"
                    value="<?php echo $address->id ?>"
                    id="address-<?php echo $this->escape($this->addressType) ?>-<?php echo $address->id ?>"
                    <?php echo ($this->selectedAddressId == $address->id) ? 'checked="checked"' : '' ?>
                />
                <label for="address-<?php echo $this->escape($this->addressType) ?>-<?php echo $address->id ?>">
                    <?php echo $this->translate('checkout')->__('Use this address')?></label>
            </h5>
            <address>
                <?php echo $this->address($address); ?>
            </address>
            <a href="<?php echo $this->href('/account/address-book/edit/id/' . $address->id, true) ?>"
                class="address-edit"><?php echo $this->translate('checkout')->__('edit')?>
            </a>
        </div>
    </td>
    <?php $i++;

    if ($i % $columnCount == 0): ?>
        </tr>
    <?php endif;

endforeach;

if ($i % $columnCount != 0) :
    for($i; $i % $columnCount; $i++): ?>
        <td>&nbsp;</td>
    <?php endfor;?>
    </tr>
<?php endif; ?>

</table>
<?php endif; ?>

    <div class="button-set">
        <?php echo $this->button($this->translate('checkout')->__('Add new address'), array(
            'class' => 'alt-button btn-add-address',
            'href' => $this->href('/account/address-book/new', true)
        )) ?>
        <?php echo $this->button($this->translate('checkout')->__('Continue'), array(
            'class' => 'button btn-continue',
            'type' => 'submit'
        ), 'button') ?>
    </div>
</div>
<?php if('billing-address' === $this->addressType):?>
<div class="label-inline">
    <input type="hidden" value="0" name="use_as_delivery"/>
    <input id="use_as_delivery" class="input-checkbox" type="checkbox" value="1" name="use_as_delivery"/>
    <label for="use_as_delivery">
        <?php echo $this->translate('checkout')->__('Ship to this address');?>
    </label>
</div>
<?php endif;?>
</form>