<?php echo $this->title($this->pageTitle) ?>

<form class="axis-form" method="post" action="<?php echo $this->href('/checkout/wizard/set-' . $this->addressType, true);?>">
    <div id="<?php echo $this->escape($this->addressType); ?>-radios">
    <?php
    if (count($this->addressList)) :
        $addressArray = array();
        foreach ($this->addressList as $address) :
            $addressArray[$address->id] = trim($this->address($address, ', '), ', ');
        endforeach;

        echo $this->formSelect(
            $this->escape($this->addressType) . '-id',
            $this->selectedAddressId,
            null,
            $addressArray
        );
    endif; ?>

    <div class="button-set">
        <?php echo $this->button($this->translate('checkout')->__('Add new address'), array(
            'class' => 'alt-button btn-add-address',
            'href' => $this->href('/account/address-book/new', true)
        )) ?>
        <?php echo $this->button($this->translate('checkout')->__('Continue'), array(
            'class' => 'button btn-continue',
            'type' => 'submit'
        ), 'button') ?>
    </div>
</div>
<?php if('billing-address' === $this->addressType):?>
<div class="label-inline">
    <input type="hidden" value="0" name="use_as_delivery"/>
    <input id="use_as_delivery" class="input-checkbox" type="checkbox" value="1" name="use_as_delivery"/>
    <label for="use_as_delivery">
        <?php echo $this->translate('checkout')->__('Ship to this address');?>
    </label>
</div>
<?php endif;?>
</form>