<?php echo $this->title($this->pageTitle) ?>

<form class="axis-form" method="post" action="<?php echo $this->href('/checkout/wizard/set-shipping-method', true);?>">
    <div>
        <?php echo $this->render('checkout/onepage/shipping.phtml');?>
        <div class="actions">
            <?php echo $this->button($this->translate('checkout')->__('Continue'), array(
                'class' => 'button btn-continue',
                'type' => 'submit'
            ), 'button') ?>
        </div>
    </div>
</form>
