<?php
$this->headScript()
    ->appendFile('js/ckeditor/ckeditor.js')
    ->appendFile('js/axis/admin/core/ckeditor.js')
    ->appendFile('js/ext-axis/src/widgets/form/CKEditor.js');

$this->headScript()
    ->appendFile('js/ext-ux/filetree/Ext.ux.FileUploader.js')
    ->appendFile('js/ext-ux/filetree/Ext.ux.FileTreePanel.js');

$this->headScript()
    ->appendFile('js/ext-axis/src/widgets/ImageBrowser.js')
    ->appendFile('js/ext-axis/src/widgets/FileTreePanel.js')
    ->appendFile('js/ext-axis/src/widgets/FileUploader.js')
    ->appendFile('js/ext-axis/src/widgets/form/ImageUploadField.js')

    ->appendFile('js/axis/admin/catalog/manufacturer/grid.js')
    ->appendFile('js/axis/admin/catalog/manufacturer/window.js');
?>