<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="robots" content="NOINDEX,NOFOLLOW" />
    <link rel="icon" href="<?php echo $this->skinUrl('favicon.ico') ?>" type="image/x-icon" />
    <link rel="shortcut icon" href="<?php echo $this->skinUrl('favicon.ico') ?>" type="image/x-icon" />
    <title><?php echo $this->translate('admin')->__('Login to Axis administrator panel') ?></title>
    <link href="<?php echo $this->skinUrl('css/auth.css') ?>" rel="stylesheet" type="text/css"/>
</head>
<body>
    <div class="login-window">
        <div class="head"><h2>Forgot password</h2><p class="powered">Powered by Axis</p></div>
        <div class="content">
            <?php echo $this->message(); ?>
            <form class="form-forgot axis-form" method="post" action="<?php echo $this->href('/forgot/register');?>">
                <p>
                    <label for="email"><?php echo $this->translate('admin')->__('Email')?></label>
                    <input class="input-text required" type="text" id="email" name="email" tabindex="1"/>
                </p>
                <p><a href="<?php echo $this->href('/');?>"><?php echo $this->translate('admin')->__('Go to login page')?></a></p>
                <button class="button btn-submit" type="submit"><span><?php echo $this->translate('admin')->__('Retrieve Your Password')?></span></button>
            </form>
        </div>
    </div>
    <script type="text/javascript">
        window.onload = function() { document.getElementById('email').focus(); }
    </script>
</body>
</html>