<?php
    $this->headScript()->appendFile('js/axis/checkout/onestep.js')
        ->appendFile('js/jquery/datepicker/ui.datepicker.js');

    $this->headLink()->appendStylesheet('js/jquery/datepicker/ui.datepicker.css');
?>

<div class="page-title">
    <h1 class="title">
        <?php echo $this->pageTitle ?>
        <?php if (!Axis::getCustomerId()) : ?>
            <?php $label = $this->translate('account')->__('Already registered? Log in, please'); ?>
            <a class="onestep-login"
                href="<?php echo $this->href('account/auth', true) ?>"
                title="<?php echo $label ?>"
            ><?php echo $label ?></a>
        <?php endif; ?>
    </h1>
</div>

<?php echo $this->message() ?>

<form method="post" action="<?php echo $this->href('checkout/onestep/process', true)?>" id="form-checkout">
    <div class="onestep-set">
        <div class="col-address">
            <?php echo $this->render('checkout/onestep/billing-address.phtml') ?>
            <?php if (Axis::config('checkout/address_form/shipping_address_enabled')) : ?>
                <?php echo $this->render('checkout/onestep/delivery-address.phtml') ?>
            <?php endif; ?>
        </div>
        <div class="col-shipping-payment">
            <?php echo $this->render('checkout/onestep/shipping-method.phtml') ?>
            <?php echo $this->render('checkout/onestep/payment-method.phtml') ?>
            <?php echo $this->render('checkout/onestep/review.phtml') ?>
        </div>
    </div>
</form>

<script type="text/javascript">
Onestep.init({
    urls: {
        billing_address : '<?php echo $this->href('checkout/onestep/update-billing-address', true) ?>',
        delivery_address: '<?php echo $this->href('checkout/onestep/update-delivery-address', true) ?>',
        shipping_method : '<?php echo $this->href('checkout/onestep/update-shipping-method', true) ?>',
        payment_method  : '<?php echo $this->href('checkout/onestep/update-payment-method', true) ?>',
        shopping_cart   : '<?php echo $this->href('checkout/onestep/update-shopping-cart', true) ?>'
    },
    zones: <?php echo Zend_Json::encode($this->checkout['form_billing_address']->getZones()); ?>,
    ajax: <?php echo Zend_Json::encode(Axis::config('checkout/onestep_ajax')->toArray()); ?>,
    messages: {
        product_remove_confirm: '<?php echo $this->translate('checkout')->__('Are you sure you want to remove this product from shopping cart?') ?>',
        request_error: '<?php echo $this->translate('core')->__('An error has been occured during request processing. Try again') ?>'
    }

});

$(document).ready(function($){
    $('.input-date').datepicker({ dateFormat: 'yy-mm-dd'});
});
</script>

<?php if (!Axis::getCustomerId()) : ?>
    <?php echo $this->render('account/auth/window-auth.phtml') ?>
<?php endif; ?>
