<div class="box order-review">
    <div class="head"><span class="title"><?php echo $this->translate('checkout')->__('Order review') ?></span></div>
    <div class="content">
        <div id="shopping-cart-load">
            <?php echo $this->render('checkout/onestep/review/cart.phtml') ?>
        </div>

        <div class="place-order-row">
            <p class="order-comment-row">
                <label for="comment"><?php echo $this->translate('checkout')->__('You can add some additional information for our manager')?>:</label><br/>
                <textarea rows="5" cols="50" class="input-text order-comment" name="comment" id="comment"></textarea>
            </p>
            <div class="submit-area">
                <?php echo $this->button($this->translate('checkout')->__('Place Order'), array(
                    'class' => 'button btn-submit',
                    'id'    => 'submit',
                    'type'  => 'submit'
                ), 'button') ?>
            </div>
        </div>
    </div>
</div>
