<?php
$this->headScript()
    ->appendFile('js/axis/admin/customer/field/valueset/grid.js')
    ->appendFile('js/axis/admin/customer/field/valueset/valueGrid.js')
    ->appendFile('js/axis/admin/customer/field/valueset/window.js')

    ->appendFile('js/axis/admin/customer/field/group.js')
    ->appendFile('js/axis/admin/customer/field/group/grid.js')
    ->appendFile('js/axis/admin/customer/field/group/window.js')

    ->appendFile('js/axis/admin/customer/field/field.js')
    ->appendFile('js/axis/admin/customer/field/field/grid.js')
    ->appendFile('js/axis/admin/customer/field/field/window.js')

    ->appendFile('js/axis/admin/customer/field/panel.js');

$this->setButtons(array(
    array(
        'title' => $this->translate('Axis_Account')->__('Value sets'),
        'class' => 'button',
        'onclick' => 'ValuesetWindow.show(); return false;'
    )
));

?>

<script type="text/javascript">
var validators = <?php echo Zend_Json::encode($this->validators) ?>;
var fieldTypes = <?php echo Zend_Json::encode($this->fieldTypes) ?>;
</script>