<?php
$this->headScript()
    ->appendFile('/js/ext-ux/multiselect/ComboSelect.js')
    ->appendFile('js/ext-axis/src/widgets/form/ComboSelect.js')
    ->appendFile('/js/axis/admin/discount/discount.js')
    ->appendFile('/js/axis/admin/discount/tabs/general.js')
    ->appendFile('/js/axis/admin/discount/tabs/site.js')
    ->appendFile('/js/axis/admin/discount/tabs/group.js')
    ->appendFile('/js/axis/admin/discount/tabs/manufacturer.js')
    ->appendFile('/js/axis/admin/discount/tabs/categories.js')
    ->appendFile('/js/axis/admin/discount/tabs/product.js')
    ->appendFile('/js/axis/admin/discount/tabs/price.js')
    ->appendFile('/js/axis/admin/discount/tabs/date.js')
    ->appendFile('/js/axis/admin/discount/window.js');
?>
<?php $this->setButtons(array(
    array(
        'title' => Axis::translate('Axis_Admin')->__('Back'),
        'onclick' => 'history.back();',
        'class' => 'alt-button'
    )
));?>
<select id="tbar-display-mode" name="tbar-display-mode">
    <option value="all">
        <?php echo $this->translate('discount')->__('Show All');?>
    </option>
    <option selected="selected" value="without-special">
        <?php echo $this->translate('discount')->__('Show without Special ');?>
    </option>
    <option value="only-special">
        <?php echo $this->translate('discount')->__('Show only Special')?>
    </option>
</select>