<div id="lightbox-info"
     style="position: absolute;
            visibility: hidden;
            left: 137px;
            top: 115px;
            width: 300px;
            height: 18px;
            background: #fff;"
></div>

<?php
$this->setButtons(array(
    array(
        'title' => 'Revoke Token',
        'class' => 'alt-button',
        'onclick' => "Ext.Ajax.request({
            url: '{$this->href('/google-base/revoke-token')}',
            method: 'get',
            callback: function() {
                window.location = '{$this->href('/google-base')}';
            }
        })"
    )
));

echo $this->formSelect('language', null, null, $this->languages);
echo $this->formSelect('gCountry', null, null, $this->gCountries);
echo $this->formSelect('targetCountry', null, null, $this->gCountries);
echo $this->formSelect('currency', null, null, $this->currencies);
?>
<script type="text/javascript">
    var localGrid, gbaseGrid;
</script>

<?php $this->headScript()->appendFile('js/axis/admin/gbase/categoryTree.js')?>
<?php $this->headScript()->appendFile('js/axis/admin/gbase/localGrid.js')?>
<?php $this->headScript()->appendFile('js/axis/admin/gbase/gbaseGrid.js')?>
<?php $this->headScript()->appendFile('js/axis/admin/gbase/productTabs.js')?>
<?php $this->headScript()->appendFile('js/axis/admin/gbase/panel.js')?>