<?php
$box      = $this->box;
$question = $box->getData('question');
$answers  = $box->getData('answers');

echo $this->message();

if (!$box->status) : ?>
<script type="text/javascript">
function validatePollBox(form) {
    var options = $('input.poll_vote', form);
    for (i in options ) {
        if (true == options[i].checked) {
            return true;
        }
    }
    return false;
}

function sendForm(form) {
    if (!validatePollBox(form)) {
        return false;
    }

    var voteBtn = $('#form-poll .btn-vote');
    voteBtn.attr('disabled', 'disabled').addClass('loading');

    $.post(form.action, $('#form-poll').serialize())
        .success(function(response) {
            $('#poll-box-wrap').html(response.content);
        })
        .error(function(response) {
            if (response.status) {
                alert('An error has been occured during request processing. Try again');
            }
        })
        .complete(function() {
            voteBtn.removeAttr('disabled').removeClass('loading');
        });

    return false;
}
</script>

<div id="poll-box-wrap">
    <form id="form-poll" onsubmit="return sendForm(this);" method="post" action="<?php echo $this->href('poll/index/save') ?>">
        <div>
            <h4><?php echo $question['question']; ?></h4>
            <?php echo $this->formHidden('questionId[]', $question['id']); ?>
            <ol>
            <?php foreach ($answers as $answer) : ?>
                <li>
                <?php if (isset($question['type']) && $question['type']) : ?>
                    <?php echo $this->formCheckbox('vote[]', $answer['id'], array('class' => 'poll_vote', 'id' => 'vote-' . $answer['id'])) ?>
                <?php else : ?>
                    <input id="vote-<?php echo $answer['id'] ?>" name="vote[]" type="radio" value="<?php echo $answer['id'];?>" class="poll_vote" />
                <?php endif;?>
                    <label for="vote-<?php echo $answer['id'] ?>"><?php
                        echo $answer['answer'];
                    ?></label>
                </li>
            <?php endforeach; ?>
            </ol>
            <div class="actions">
                <a href="<?php echo $this->href('poll/index/index/showResult/1/questionId/' . $question['id'])?>">
                    <?php echo $this->translate('poll')->__('View Results');?>
                </a>
                <?php echo $this->button($this->translate('poll')->__('Vote'), array(
                    'class' => 'button btn-vote f-right',
                    'type' => 'submit'
                ), 'button') ?>
            </div>
        </div>
    </form>
</div>
<?php else : ?>
    <?php $results = $box->results;?>
    <h4><?php echo $question['question']; ?></h4>
    <ul class="chart-list no-bullet no-indent">
    <?php  foreach ($answers as $answer) : ?>
        <li>
            <p><?php echo $answer['answer'];?></p>
            <p class="chart-list-bar"><?php
                $percent = false;
                $count = 0;
                if (isset($results[$answer['id']])) :
                    $count = $results[$answer['id']]['cnt'];
                    $percent = round($count * 100 / $box->total_count, 2);
                endif;?>
                <span class="count"><?php
                    echo $count;?> (<?php echo $percent ? $percent : 0;?>%)
                </span>
                <span class="index-wrapper">
                    <span style="width: <?php
                        echo $percent ? $percent . '%' : '1px'?>;" class="index">
                        <?php echo $this->translate('poll')->__('overall')?>
                    </span>
                </span>
            </p>
        </li>
    <?php endforeach; ?>
</ul>
<?php endif;?>