<form method="post" action="<?php echo $this->href('core/config_value/save');?>" id="form-edit"
      onsubmit="Config.save(); return false;">
<?php
    echo $this->formHidden('siteId', $this->siteId);
    echo $this->formHidden('path', $this->row->path);
?>
<h3 class="config-title"> <?php echo $this->row->title;?> </h3>
<dl class="general-form">
    <?php if (!empty($this->row->description)) : ?>
        <dt><label><?php echo $this->translate('admin')->__('Description');?>: </label></dt>
        <dd><?php echo $this->row->description;?></dd>
    <?php endif; ?>
    <dt><label for="confValue"><?php echo $this->translate('admin')->__('Value');?>:</label></dt>
    <dd><?php
    //@todo echo $this->render($this->row->config_type)
    switch ($this->row->config_type) {
        case 'bool':
            echo $this->bool('confValue', $this->value, $this->options);
            break;
        case 'select':
            echo $this->select('confValue', $this->value, $this->options);
            break;
        case 'multiple':
            echo $this->multiple('confValue', $this->value, $this->options);
            break;
        case 'text':
            echo $this->text('confValue', $this->value);
            break;
        case 'multiprice':
            echo $this->render('shippingflat/standard/multiprice.phtml');
            break;

        default:
            echo $this->string('confValue', $this->value);
    }
    ?></dd>
</dl>
</form>