<?php $this->headScript()->appendFile('/js/axis/admin/contacts/contact-us.js'); ?>

<script type"text/javascript">
var sites = [
    <?php
    $str = '';
    foreach (Axis_Core_Model_Site::collect() as $id => $name) {
        $name = addslashes($name);
        $str .= "[$id, '$name'],\n";
    }
    echo substr($str, 0, -2);
    ?>
];
var departaments = [
    <?php
    $str = '';
    foreach (Axis_Contacts_Model_Department::collect() as $id => $name) {
        $name = addslashes($name);
        $str .= "[$id, '$name'],\n";
    }
    echo substr($str, 0, -2);
    ?>
];
var statuses = [['new', 'New'.l()], ['read', 'Readed'.l()], ['replied', 'Replied'.l()]];
</script>

<div id="tpl-message" class="x-hidden">
<table width="100%" cellpadding="3" class="axis-table">
    <tr valign="top">
      <td><strong><?php echo $this->translate('contacts')->__('From')?>:</strong></td>
      <td width="100%">{from}</td>
    </tr>
    <tr valign="top">
      <td><strong><?php echo $this->translate('contacts')->__('Subject')?>:</strong></td>
      <td>{subject}</td>
    </tr>
    <tr valign="top">
      <td><strong><?php echo $this->translate('contacts')->__('Message')?>:</strong></td>
      <td>{message}</td>
    </tr>
    <tr valign="top">
      <td> <strong><?php echo $this->translate('contacts')->__('Custom fields')?>:</strong></td>
      <td>{custom}</td>
    </tr>
    <tr valign="top">
      <td><strong><?php echo $this->translate('contacts')->__('Date&amp;Time')?>:</strong></td>
      <td>{datetime}</td>
    </tr>
</table>
</div>