<?php echo $this->title($this->pageTitle) ?>
<p>
    <strong>
    <?php echo $this->translate('checkout')->__("Thank You! We Appreciate your Business!")?>
    </strong>
</p>
<?php if ($this->orderId) :?>
    <p>
        <?php echo $this->translate('checkout')->__("Your Order Number is")?>: <?php echo $this->orderId;?>
        <a href="<?php echo $this->href('/account/order/view/orderId/' . $this->orderId, true) ?>"><?php echo $this->translate('checkout')->__('View')?></a>
    </p>
<?php endif;?>

<p>
    <?php echo $this->translate('checkout')->__("Checkout Success Sample Text ...");?>
</p>
<p>
    <?php echo $this->translate('checkout')->__("Thank you for shopping. Please click the Log Off link to ensure that your receipt and purchase information is not visible to the next person using this computer.")?>
</p>
<p>
    <?php echo $this->translate('checkout')->__('You can view your order history by going to the "%s" page and by clicking on "View All Orders".
    Please direct any questions you have to customer service.',
    "<a href=\" {$this->href('/account/order', true)}\">{$this->translate('checkout')->__('My Account Orders')}</a>")?>
</p>