<table cellspacing="0" cellpadding="5" border="0" width="650" style="background: #eee; border: 1px solid #bbb;margin-top:10px;" class="footer">
    <tr>
        <td class="copyright" style="font-size:10px;color:#666;padding:5px;">
            <?php echo $this->translate('core')->__('Copyright')?> &copy; <?php echo Axis_Date::now()->toString('Y'); ?>
            <a href="<?php echo $this->href('', false, false) ?>"><?php echo $this->siteName ?></a>
        </td>
    </tr>
</table>