<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<style type="text/css">
    body {color:#000;font:11px/1.35em Verdana, Arial, Helvetica, sans-serif;padding: 0px;margin: 0px;}
    td, th {font:11px/1.35em Verdana, Arial, Helvetica, sans-serif;padding:5px;}
    p {margin: 1px 0 4px;}
    a {color:#0066cc;}
    a:hover {text-decoration:none;color:#0066cc;}
    a:visited {color:#0066cc;}
    a img {border:none;}
    .header {font-size:10px;padding:0px;width:550px;}
    .content {font-size:10px;padding:5px;width:550px;}
    .footer {color:#666;border-top:1px solid #9a9a9a;font-size:9px;margin-top:10px;width:550px;}
    .disclaimer {color:#666;background-color:#f9f9f9;border:1px solid #cccccc;font-size:10px;margin-top:10px;padding:5px;width:550px;}
    .disclaimer1 {padding:5px;font-size:10px;}
    .disclaimer2 {padding:5px;font-size:10px;}
    .copyright {padding:5px;}
</style>