<div class="col3-set">
    <div class="billing-address address col-1">
        <div class="head">
            <h4 class="address-title">
                <?php echo $this->translate('checkout')->__('Billing Address');?>
            </h4>
        </div>
        <address>
            <?php echo $this->translate('PaymentPaypal')->__('Paypal Account')?><br/>
            <?php echo $this->checkout['email'];?><br/>
        </address>
        <div class="foot">
            <h5><?php echo $this->translate('checkout')->__('Payment Method'); ?>:</h5>
            <h4><?php echo $this->translate('PaymentPaypal')->__('Paypal Express Checkout'); ?></h4>
        </div>
        <a class="address-edit" href="<?php echo $this->href('/paymentpaypal/express-checkout/edit', true); ?>">
            <?php echo $this->translate('checkout')->__('Change Payment Method')?>
        </a>
    </div>
    <div class="shipping-address address col-2">
        <div class="head">
            <h4 class="address-title">
                <?php echo $this->translate('checkout')->__('Delivery Address'); ?>
            </h4>
        </div>
        <address>
                <?php echo $this->address($this->checkout['delivery']); ?>
        </address>
        <div class="foot">
            <h5><?php echo $this->translate('checkout')->__('Shipping Method');?>:</h5>
            <p><?php echo $this->checkout['shipping']; ?></p>
        </div>
        <a class="address-edit" href="<?php echo $this->href('/paymentpaypal/express-checkout/edit', true);?>">
            <?php echo $this->translate('checkout')->__('Change Address')?>
        </a>
    </div>
</div>
<br/>

<table cellspacing="0" cellpadding="1" border="0" id="shopping-cart-table" class="data-table">
<thead>
    <tr>
        <th><?php echo $this->translate('checkout')->__('Product')?></th>
        <th><?php echo $this->translate('checkout')->__('Price')?></th>
        <th><?php echo $this->translate('checkout')->__('Quantity')?></th>
        <th><?php echo $this->translate('checkout')->__('Final price')?></th>
    </tr>
</thead>
<tbody>
    <?php foreach ($this->checkout['products'] as $itemId => $product) : ?>
    <tr valign="top">
        <td>
            <?php echo $product['name'];?><br />
            <?php foreach ($product['attributes'] as $attr) { ?>
                <div><small><?php
                    echo $attr['product_option'] . ': ' . $attr['product_option_value'];
                ?> </small></div>
            <?php } ?>
        </td>
        <td><?php echo $this->currency($product['final_price']);?></td>
        <td class="a-center"><?php echo $product['quantity']?></td>
        <td><?php echo $this->currency($product['quantity'] * $product['final_price']);?></td>
    </tr>
    <?php endforeach; ?>

    <?php foreach ($this->checkout['totals'] as $total) : ?>
        <tr>
            <td colspan="3" class="a-right"><?php echo $this->translate('checkout')->__($total['title']) ?>:</td>
            <td ><?php echo $this->currency($total['total'])?></td>
        </tr>
    <?php endforeach; ?>

    <tr>
        <td colspan="3" class="a-right">
            <?php echo $this->translate('checkout')->__('Total')?>:
        </td>
        <td><?php echo $this->currency($this->checkout['total'])?></td>
    </tr>
</tbody>

<tfoot>
    <tr>
        <td colspan="100" class="a-right">
            <form method="post" action="<?php echo $this->href('/paymentpaypal/express-checkout/process', true);?>" id="form-checkout">
                <p class="order-comment-row">
                    <label for="comment"><?php echo Axis::translate('checkout')->__('You can add some additional information for our manager')?>:</label><br/>
                    <textarea rows="5" cols="80" class="input-text order-comment" name="comment" id="comment"></textarea>
                </p>
                <?php echo $this->button($this->translate('checkout')->__('Create Order'), array(
                    'class' => 'button btn-confirm',
                    'type' => 'submit'
                ), 'button') ?>
            </form>
        </td>
    </tr>
</tfoot>
</table>