<div <?php if (null == $this->priceValue) echo 'id="condition-price-template"'; ?>>
    <label><?php echo $this->translate('discount')->__("Price")?></label>
    <div class="col2">
        <select name="condition[price][e-type][]">
        <?php foreach (Axis_Discount_Model_Discount::getPriceConditionTypes() as $value => $caption) {
            echo "<option value='$value' "
                . ($value == $this->priceEqualType ? 'selected="1"' : '')
                . ">$caption</option>";
        } ?>
        </select>
        <?php echo $this->formText('condition[price][value][]', $this->priceValue); ?>
    </div>
    <input type="button" class="delete-img" value="" onclick="deleteCondition(this)" />
</div>