<?php echo "<?"?>php

$config = array(
    'system' => array(
        'path'    => '<?php echo $this->config['store_path'] ?>'
    ),
    
    'crypt' => array(
        'key' => '<?php echo $this->config['store_cryptKey'] ?>'
    ),
    
    'db' => array(
        'host'     => '<?php echo $this->config['db_host'] ?>',
        'username' => '<?php echo $this->config['db_username'] ?>',
        'password' => '<?php echo str_replace("'", "\\'", $this->config['db_password']) ?>',
        'dbname'   => '<?php echo $this->config['db_dbname'] ?>',
        'prefix'   => '<?php echo $this->config['db_prefix'] ?>'
    ),
    
    'front' => array(
        'humanUrlAdapter' => "Readable"
    )
);
