<table class="data-table requirements-table">
    <thead>
        <tr>
            <th><?php echo $this->t('Title') ?></th>
            <th><?php echo $this->t('Expected Value') ?></th>
            <th><?php echo $this->t('Server Value') ?></th>
            <th><?php echo $this->t('Success') ?></th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->requirements as $groupTitle => $group) : ?>
    <tr class="group-row">
        <td colspan="100"><strong><?php echo $this->t($groupTitle) ?></strong></td>
    </tr>
    <?php foreach ($group as $option) : ?>
        <tr class="option-row row-<?php echo $option['success'] ? 'success' : 'failure' ?>">
            <td class="title"><?php echo $this->t($option['title']) ?></td>
            <td class="expected"><?php echo $this->t($option['expected']) ?></td>
            <td class="server"><?php echo $this->t($option['value']) ?></td>
            <td class="result"><?php echo $option['success'] ?></td>
        </tr>
    <?php endforeach; ?>
<?php endforeach; ?>
    </tbody>
</table>

<form action="<?php echo $this->baseUrl; ?>/index/check-requirements">
<div class="button-set">
    <?php 
    $params['type'] = 'submit';
    if (!$this->isValid) :
        $params['disabled'] = 'disabled';
    endif;
    echo $this->button($this->t('Continue'), $params) ?>
    <?php if (!$this->isValid) : ?>
        <?php echo $this->button($this->t('Refresh'), array(
            'href' => $this->baseUrl . '/index/step-requirements',
            'class' => 'button f-right'
        ), 'link') ?>
    <?php endif; ?>
</div>
</form>
