<form id="form-user" action="<?php echo $this->baseUrl?>/index/save-user" method="post">
    <fieldset class="group-select">
        <legend><span><?php echo Axis::translate('install')->__('Administrator account') ?></span></legend>
        <h4 class="legend"><?php echo Axis::translate('install')->__('Administrator account') ?></h4>
        <ul>
        <li>
            <label for="email"><?php echo Axis::translate('install')->__('Email')?><span class="required">*</span>:</label><br/>
            <input name="email" id="email" type="text" class="required input-text" value="<?php echo $this->email ?>"/>
        </li>
        <li>
            <div class="col2-set">
                <div class="col-1">
                    <label for="name"><?php echo Axis::translate('install')->__('Firstname')?><span class="required">*</span>:</label><br/>
                    <input name="name" id="name" type="text" class="required input-text" value="<?php echo $this->firstname ?>"/>
                </div>
                <div class="col-2">
                    <label for="surname"><?php echo Axis::translate('install')->__('Lastname')?><span class="required">*</span>:</label><br/>
                    <input name="surname" id="surname" type="text" class="required input-text" value="<?php echo $this->lastname ?>"/>
                </div>
            </div>
        </li>
        <li>
            <label for="login"><?php echo Axis::translate('install')->__('Username')?><span class="required">*</span>:</label><br/>
            <input name="login" id="login" type="text" class="required input-text" value="<?php echo $this->login ?>"/>
            <small><?php echo Axis::translate('install')->__('This name you will need to access to store backend')?></small>
        </li>
        <li>
            <label for="password"><?php echo Axis::translate('install')->__('Password')?><span class="required">*</span>:</label><br/>
            <input name="password" id="password" type="password" class="required input-text"/>
        </li>
        </ul>
    </fieldset>

<div class="button-set">
    <?php echo $this->button(Axis::translate('install')->__('Back'), array(
        'onclick' => "window.location='" . $this->baseUrl . "/index/step-configuration'; return false;",
        'class' => 'alt-button',
        'type' => 'button'
    )) ?>
    <?php echo $this->button(Axis::translate('install')->__('Install'), array(
        'type'  => 'submit',
        'id'    => 'submit'
    )) ?>
</div>
</form>
<script type="text/javascript">
jQuery('document').ready(function() {
    Spinner.message = '<?php echo Axis::translate('install')->__("Installing. Please wait...") ?>';
    $('#form-user').submit(function() {
        $('button#submit').attr('disabled', 'disabled');
        Spinner.show();
    });
});
</script>