<form id="form-db" action="<?php echo $this->baseUrl?>/index/save-configuration" method="post">
    <fieldset class="group-select">
        <legend><span><?php echo Axis::translate('install')->__('Database connection')?></span></legend>
        <h4 class="legend"><?php echo Axis::translate('install')->__('Database connection')?></h4>
        <dl>
            <dt>
                <label for="host" ><?php echo Axis::translate('install')->__('Database Server')?><span class="required">*</span>:</label>
            </dt>
            <dd>
                <?php echo $this->formText('host', empty($this->db['host']) ? 'localhost' : $this->db['host']) ?>
                <small><?php echo Axis::translate('install')->__('The address of the database server in the form of a hostname or IP address')?></small>
            </dd>
            <dt>
                <label for="database"><?php echo Axis::translate('install')->__('Database Name')?><span class="required">*</span>:</label>
            </dt>
            <dd>
                <?php echo $this->formText('database', empty($this->db['dbname']) ? 'axis' : $this->db['dbname']) ?>
                <small><?php echo Axis::translate('install')->__('The name of the database to hold the data in')?></small>
            </dd>
            <dt>
                <label for="prefix"><?php echo Axis::translate('install')->__('Table prefix')?>:</label>
            </dt>
            <dd>
                <?php echo $this->formText('prefix', $this->db['prefix']) ?>
            </dd>
            <dt>
                <label for="username"><?php echo Axis::translate('install')->__('Username')?><span class="required">*</span>:</label>
            </dt>
            <dd>
                <?php echo $this->formText('username', empty($this->db['username']) ? 'root' : $this->db['username']) ?>
                <small><?php echo Axis::translate('install')->__('The username used to connect to the database server')?></small>
            </dd>
            <dt>
                <label for="password"><?php echo Axis::translate('install')->__('Password')?>:</label>
            </dt>
            <dd>
                <?php echo $this->formPassword('password') ?>
                <small><?php echo Axis::translate('install')->__('The password that is used together with the username to connect to the database server')?></small>
            </dd>
        </dl>
    </fieldset>
    
    <fieldset class="group-select">
        <legend><span><?php echo Axis::translate('install')->__('Web access options')?></span></legend>
        <h4 class="legend"><?php echo Axis::translate('install')->__('Web access options')?></h4>
        <dl>
            <dt>
                <label for="base_url"><?php echo Axis::translate('install')->__('Base Url')?><span class="required">*</span>:</label>
            </dt>
            <dd>
                <?php echo $this->formText('base_url', $this->store['base_url'], array('size' => 50)) ?>
                <small><?php echo Axis::translate('install')->__('Frontend Url')?></small>
            </dd>
            <dt>
                <label for="admin_url"><?php echo Axis::translate('install')->__('Admin Path')?><span class="required">*</span>:</label>
            </dt>
            <dd>
                <?php echo $this->formText('admin_url', $this->store['admin_url'], array('size' => 50)) ?>
                <small><?php echo Axis::translate('install')->__('Administrative panel path')?></small>
            </dd>
            <?php if (!function_exists('apache_get_modules') || in_array('mod_ssl', apache_get_modules())) : ?>
            <dd>
                <?php
                    $params = array(
                        'onchange' => "$('#secure_url').parent().toggle(); $('#secure_url_label').parent().toggle();"
                    );
                    if (true == $this->store['use_ssl']) {
                        $params['checked'] = 'checked';
                    }
                 ?>
                <?php echo $this->formCheckbox('enable_ssl', true, $params) ?>
                <label for="enable_ssl"><?php echo Axis::translate('install')->__('Use Secure URLs (SSL)')?></label>
            </dd>
            <dt style="display: <?php echo isset($params['checked']) ? 'block' : 'none' ?>">
                <label id="secure_url_label" for="secure_url"><?php echo Axis::translate('install')->__('Secure Url')?>:</label>
            </dt>
            <dd style="display: <?php echo isset($params['checked']) ? 'block' : 'none' ?>">
                <?php echo $this->formText('secure_url', $this->store['secure_url'], array('size' => 50)) ?>
                <small><?php echo Axis::translate('install')->__('Site secure url')?></small>
            </dd>
            <?php endif; ?>
            
        </dl>
    </fieldset>
    
    <fieldset class="group-select">
        <legend><span><?php echo Axis::translate('install')->__('Store configuration')?></span></legend>
        <h4 class="legend"><?php echo Axis::translate('install')->__('Store configuration')?></h4>
        <dl>
            <dt>
                <label for="crypt_key"><?php echo Axis::translate('install')->__('Encription Key')?><span class="required">*</span>:</label>
            </dt>
            <dd>
                <?php echo $this->formText('crypt_key', $this->store['crypt_key'], array('size' => 50)) ?>
                <small><?php echo Axis::translate('install')->__('Key that will be used to encrypt private data like passwords, usernames, credit cards etc.')?></small>
            </dd>
        </dl>    
    </fieldset>

<div class="button-set">
    <?php echo $this->button(Axis::translate('install')->__('Back'), array(
        'onclick' => "window.location='" . $this->baseUrl . "/index/step-localization'; return false;",
        'class' => 'alt-button',
        'type' => 'button'
    )) ?>
    <?php echo $this->button(Axis::translate('install')->__('Continue'), array(
        'type' => 'submit'
    )) ?>
</div>
</form>