<form id="form-locale" action="<?php echo $this->baseUrl?>/index/save-localization" method="post">
<fieldset class="group-select">
    <legend><span><?php echo Axis::translate('install')->__('Default locale settings') ?></span></legend>
    <h4 class="legend"><?php echo Axis::translate('install')->__('Default locale settings') ?></h4>
    <ul>
        <li>
            <div class="input-box">
                <label for="default-locale"><?php echo Axis::translate('install')->__('Locale')?>:</label><br/>
                <?php echo $this->formSelect('default[locale]', Axis_Locale::getLocale(), null, Axis::model('locale/option_zendLocale')->toArray()) ?>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="default-timezone"><?php echo Axis::translate('install')->__('Timezone')?>:</label><br/>
                <?php echo $this->formSelect('default[timezone]', Axis_Locale_Model_Timezone::getTimezone(), null, Axis::model('locale/option_zendTimezone')->toArray()) ?>
            </div>
            <div class="input-box">
                <label for="default-currency"><?php echo Axis::translate('install')->__('Currency')?>:</label><br/>
                <?php $currency = new Zend_Currency(); ?>
                <?php echo $this->formSelect('default[currency]', $currency->getShortName(),  null, Axis::model('locale/option_zendCurrency')->toArray()) ?>
            </div>
        </li>
    </ul>
</fieldset>

<fieldset class="group-select">
    <legend><span><?php echo Axis::translate('install')->__('Additional locales') ?></span></legend>
    <h4 class="legend"><?php echo Axis::translate('install')->__('Additional locales') ?></h4>
    <div class="clear"></div>
    <button type="button" id="add-locale" onclick="Locale.addLocale();"><span><?php echo Axis::translate('install')->__('Add Locale') ?></span></button>
    <button type="button" id="add-currency" onclick="Locale.addCurrency();"><span><?php echo Axis::translate('install')->__('Add Currency') ?></span></button>
    <div class="col2-set">
        <div id="additional-locale" class="col-1"></div>
        <div id="additional-currency" class="col-2"></div>
    </div>
</fieldset>
<div class="button-set">
    <?php echo $this->button(Axis::translate('install')->__('Continue'), array(
        'type' => 'submit'
    )) ?>
</div>
</form>