<?php if (!isset($this->permitInstallation)) : ?>
    <p>You should not be here</p>
<?php endif; ?>
<ul class="disc">
    <li>
        <?php echo Axis::translate('install')->__(
            "Go to %s",
            "<a href='" . $this->frontend . "'
                onclick='window.open(this.href);return false;'>" . Axis::translate('install')->__('Frontend') .
            "</a>") ?>
    <li>
        <?php echo Axis::translate('install')->__(
            "Go to %s",
            "<a href='" . $this->backend . "'
                onclick='window.open(this.href);return false;'>" . Axis::translate('install')->__('Backend') .
            "</a>") ?>
        <ul class="disc">
            <li><?php echo Axis::translate('install')->__('Username') ?>: <?php echo $this->user_login; ?></li>
            <li><?php echo Axis::translate('install')->__('Password') ?>: <?php echo $this->user_password; ?></li>
        </ul>
    </li>
    <li><?php echo Axis::translate('install')->__('Crypt key') ?>: <?php echo $this->crypt_key; ?>
        <strong><?php echo Axis::translate('install')->__('IMPORTANT! Make sure you keep it in a safe place.') ?></strong>
    </li>
</ul>