<table cellspacing="0" cellpadding="5" width="100%" class="table-order">
    <tr class="order-header" style="background-color: #7d7a7a; color:#fff;">
        <td colspan="2">
            <?php echo $this->translate('core')->__('Order')?> #<?php echo $this->order['number'] ?>
            <?php $date = new Axis_Date($this->order['date_purchased_on']); ?>
            :: <?php echo $date->toString(); ?>
        </td>
    </tr>
    <tr class="info-title" style="background-color: #e8e8e8;">
        <td><?php echo $this->translate('core')->__('Billing Address');?></td>
        <td><?php echo $this->translate('core')->__('Delivery Address');?></td>
    </tr>
    <tr>
        <td>
            <?php echo $this->address($this->order->getBilling()) ?>
        </td>
        <td>
            <?php echo $this->address($this->order->getDelivery()) ?>
        </td>
    </tr>
    <tr class="no-border" style="border:none;height:20px;">
        <td colspan="2"></td>
    </tr>
    <tr class="info-title" style="background-color: #e8e8e8;">
        <td><?php echo $this->translate('checkout')->__('Payment Method');?></td>
        <td><?php echo $this->translate('checkout')->__('Shipping Method');?></td>
    </tr>
    <tr>
        <td>
            <?php echo $this->escape($this->order['payment_method']) ?><br/>
        </td>
        <td>
            <?php echo $this->escape($this->order['shipping_method']) ?><br/>
        </td>
    </tr>
    <tr>
        <td>
            <?php echo $this->paymentForm($this->order['payment_method_code'], 'view', 'front') ?><br/>
        </td>
        <td>
            <?php echo $this->shippingForm($this->order['shipping_method_code'], 'view', 'front') ?><br/>
        </td>
    </tr>
</table>
<table cellspacing="0" cellpadding="5" width="100%" class="table-products">
    <tr class="info-title" style="background-color: #e8e8e8;">
        <td><?php echo $this->translate('catalog')->__('Product');?></td>
        <td><?php echo $this->translate('catalog')->__('Sku');?></td>
        <td style="width:25px;"><?php echo $this->translate('sales')->__('Qty');?></td>
        <td><?php echo $this->translate('checkout')->__('Subtotal');?></td>
    </tr>
    <?php foreach ($this->order->getProducts() as $product) : ?>
        <tr>
            <td><?php echo $this->escape($product['name']) ?>
            <?php if (isset($product['attributes'])): ?>
                <br/>
                <?php
                foreach ($product['attributes'] as $attr) {
                    echo $this->escape($attr['product_option']) . ': '
                       . $this->escape($attr['product_option_value']) . "<br />\n";
                }?>
            <?php endif; ?>
            </td>
            <td><?php echo $this->escape($product['sku']) ?></td>
            <td style="width:25px;"><?php echo $product['quantity'] ?></td>
            <td><?php echo $this->currency($product['quantity'] * $product['final_price']) ?></td>
        </tr>
    <?php endforeach; ?>
</table>
<table cellspacing="0" width="100%" style="margin-top:10px;text-align:right;" class="table-totals">
    <?php foreach ($this->order->getTotals() as $total) : ?>
        <tr>
            <td style="text-align:right;"><?php echo $this->translate('checkout')->__($total['title']) ?>:</td>
            <td style="width:20%; text-align:left; padding-left:10px;"><?php echo $this->currency($total['value'])?></td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <td style="text-align:right;"><?php echo $this->translate('checkout')->__('Total');?>:</td>
        <td style="width:20%; text-align:left; padding-left:10px;"><?php echo $this->currency($this->order['order_total']) ?></td>
    </tr>
</table>