<script type="text/javascript">
    var sites = <?php echo Zend_Json_Encoder::encode($this->sitesList);?>;
    Axis.pages = <?php echo Zend_Json::encode($this->pages) ?>;
</script>

<?php


$this->headScript()
    //plugins
    ->appendFile('/js/ext-ux/multiselect/ComboSelect.js')
    ->appendFile('js/ext-axis/src/widgets/form/ComboSelect.js')
    ->appendFile('/js/jquery/jquery.selectboxes.js')
    //gui
    ->appendFile('/js/axis/admin/poll/poll.js')
    ->appendFile('/js/axis/admin/poll/grid.js')
    ->appendFile('/js/axis/admin/poll/windowResult.js')
    ->appendFile('/js/axis/admin/poll/windowEdit.js');
?>