<?php echo $this->title($this->pageTitle) ?>

<form method="post" action="<?php echo $this->href('/paymentpaypal/express/set-shipping-method', true);?>">
    <div>
        <?php echo $this->render('checkout/onepage/shipping.phtml');?>
        <?php echo $this->button($this->translate('checkout')->__('Continue'), array(
            'class' => 'button btn-continue',
            'type' => 'submit'
        ), 'button') ?>
    </div>
</form>
