<script type="text/javascript">
Ext.namespace('Axis', 'Axis.Template');
Axis.pages = <?php echo Zend_Json::encode($this->pages) ?>;
Axis.boxClasses = <?php echo Zend_Json::encode($this->boxClasses) ?>;
</script>
<?php
$this->headScript()
    ->appendFile('js/ext-ux/multiselect/ComboSelect.js')
    ->appendFile('js/ext-axis/src/widgets/form/ComboSelect.js')

    ->appendFile('js/axis/admin/template/index/box.js')
    ->appendFile('js/axis/admin/template/index/box/grid.js')
    ->appendFile('js/axis/admin/template/index/box/tabs/general.js')
    ->appendFile('js/axis/admin/template/index/box/tabs/output.js')

    ->appendFile('js/axis/admin/template/index/layout.js')
    ->appendFile('js/axis/admin/template/index/template.js');

$this->headScript()
    ->offsetSetFile(10000, 'js/axis/admin/template/index/box/window.js');

$this->setButtons(array(
    array(
        'title' => Axis::translate('Axis_Admin')->__('Create template'),
        'class' => 'button',
        'onclick' => "Axis.Template.Template.create()"
    ),
    array(
        'title' => Axis::translate('Axis_Admin')->__('Import template'),
        'class' => 'button',
        'onclick' => "Axis.Template.Template.startImport()"
    )
));
?>