<?php echo $this->title($this->pageTitle) ?>
<div class="category-content box">
<div class="description"><?php echo $this->category['description']; ?></div>
<?php if (sizeof($this->category['childs'])) { ?>
<ul class="no-bullet">
    <?php foreach ($this->category['childs'] as $cat) { ?>
    <li>
        <a href="<?php echo $this->url(array(
            'cat' => $cat['link']),
            'cms_category', true
        ); ?>"
            class="icon-folder">
        <?php echo ($cat['title'] == '' ? $cat['link'] : $cat['title']); ?>
        </a>
    </li>
    <?php } ?>
</ul>
<?php }  ?>
<?php if (sizeof($this->category['pages'])) { ?>
<ul class="no-bullet">
    <?php foreach ($this->category['pages'] as $page) { ?>
    <li class="page">
        <a href="<?php echo $this->url(array(
            'page' => $page['link']),
            'cms_page', true
        ); ?>"
            class="icon-page">
        <?php echo ($page['title'] == '' ? $page['link'] : $page['title']); ?>
        </a>
    </li>
    <?php } ?>
</ul>
<?php } ?>
</div>