<?php $columnCount = $this->box->getColumnsCount(); ?>
<div class="product-listing product-listing-grid grid-wide grid-wide-<?php echo $columnCount ?>-cols" id="<?php echo $this->box->getData('class') ?>">
<?php
$reviewSummaryBox = $this->box('community/ReviewRating')
    ->setProductIds(array_keys($this->box->getData('products')));

$i = 0;
foreach ($this->box->getData('products') as $prodId => $product) :
    $url = $this->hurl(array(
        'product' => array('value' => $prodId, 'seo' => $product['key_word']),
        'module' => 'Axis_Catalog',
        'controller' => 'index',
        'action' => 'product'
    ), false, true);
?>
    <?php if ($i % $columnCount == 0) : ?>
        <ul class="grid-row">
    <?php endif; ?>

        <li class="product-item">
            <div class="product-image">
                <?php
                $imagePath = isset($product['images'][$product['image_listing']]) ?
                    $product['images'][$product['image_listing']]['path'] : '';
                $imageTitle = isset($product['images'][$product['image_listing']]) ?
                    $product['images'][$product['image_listing']]['title'] : '';
                ?>
                <a href="<?php echo $url ?>"
                    title="<?php echo $this->escape($imageTitle) ?>"
                ><?php
                echo $this->imager('/product' . $imagePath, array(
                    'width'  => $this->config()->image->product->widthSmall,
                    'height' => $this->config()->image->product->heightSmall,
                    'alt' => $this->escape($imageTitle),
                    'seo' => $product['image_seo_name']
                ));?></a>
            </div>
            <div class="product-info">
                <h4 class="product-name"><a href="<?php echo $url;?>"
                    title="<?php echo $this->escape($product['name']) ?>"
                    ><?php echo $this->escape($product['name']) ?></a></h4>

                <?php echo $reviewSummaryBox->setProductId($product['id'])
                    ->setProductUrl($product['key_word'])
                    ->setSmallStars(true) ?>

                <?php echo $this->price($product['prices']) ?>

                <?php if ($product['is_saleable']): ?>
                    <?php echo $this->button($this->translate('catalog')->__('Add to cart'), array(
                        'class' => 'button btn-add-to-cart',
                        'rel' => 'nofollow',
                        'href' => $this->href('checkout/cart/add/productId/' . $prodId, true)
                    )) ?>
                <?php else: ?>
                    <div class="out-of-stock"><?php echo $this->translate('catalog')->__('Out of stock') ?></div>
                <?php endif ?>
            </div>
        </li>

    <?php $i++;

    if ($i % $columnCount == 0) : ?>
       </ul>
    <?php endif;

endforeach;

if ($i % $columnCount != 0) : ?>
</ul>
<?php endif; ?>

</div>

<script type="text/javascript">
    var rows = $("#<?php echo $this->box->getData('class') ?> .grid-row");
    var count = rows.length;
    if (count) {
        $(rows[0]).addClass('first');
        $(rows[count - 1]).addClass('last');
    }
</script>