<ul>
<?php
$reviewSummaryBox = $this->box('community/ReviewRating')
    ->setProductIds(array_keys($this->box->getData('products')));
    
foreach ($this->box->getData('products') as $prodId => $product) :
    $url = $this->hurl(array(
        'product' => array('value' => $prodId, 'seo' => $product['key_word']),
        'module' => 'Axis_Catalog',
        'controller' => 'index',
        'action' => 'product'
    ), false, true);
?>    
    <li><h4 class="product-name"><a href="<?php echo $url;?>"
        title="<?php echo $this->escape($product['name']) ?>"
        ><?php echo $this->escape($product['name']) ?></a></h4></li>    
<?php endforeach ?>
</ul>