<?php echo $this->title($this->pageTitle) ?>

<?php
    $this->headScript()->appendFile('js/jquery/datepicker/ui.datepicker.js');
    $this->headLink()->appendStylesheet('js/jquery/datepicker/ui.datepicker.css');
?>

<div class="register-box">
<?php echo $this->formSignup->render($this) ?>
</div>
<script type="text/javascript">
$("#form-signup").validate({
    rules: {
        password: {
            required: true
        },
        password_confirm: {
            required: true,
            equalTo: '#password'
        }
    },
    messages: {
        password_confirm: {
            equalTo: "<?php echo $this->translate('core')->__('Please repeat the same password') ?>"
        }
    }
});

$(document).ready(function($){
    $('.input-date').datepicker({ dateFormat: 'yy-mm-dd'});
});
</script>
