<?php
$hasVisibleProperties = false;
foreach ($this->product['properties'] as $property) {
    if (!$property['visible']) {
        continue;
    }
    $hasVisibleProperties = true;
    break;
}

if ($hasVisibleProperties) : ?>
<div class="product-properties">
    <dl class="product-properties-list">
    <?php foreach ($this->product['properties'] as $property) :
        if (!$property['visible']):
            continue;
        endif;
     ?>
        <dt>
            <label>
            <?php if (!empty($property['description'])) : ?>
                <acronym title="<?php echo $this->escape($property['description']) ?>"
                    ><?php echo $this->escape($property['name']) ?></acronym>
            <?php else: ?>
                <?php echo $this->escape($property['name']) ?>
            <?php endif; ?>
            </label>
        </dt>
        <dd>
            <?php
                if (!empty($property['value']) || 0 == $property['value']) :
                    echo $property['value'];
                else:
                    echo $this->translate('catalog')->__('Empty');
                endif;
            ?>
        </dd>
    <?php endforeach; ?>
    </dl>
</div>
<?php endif ?>
