<script>
    function updateSearchIndex(skipConfirm, resetSession) {
        if (!skipConfirm
            && !confirm(("Are you sure want to delete old price indexes " +
            "and create new for all products?\nThis can take a while.").l())) {

            return;
        }
        Ext.Ajax.request({
            url: Axis.getUrl('catalog_index/update-search-index'),
            params: {
                limit       : 50,
                reset_session: resetSession
            },
            success: function(response, options) {
                response = Ext.decode(response.responseText);
                if (false == response.completed) {
                    updateSearchIndex(1, 0);
                }
            }
        });
    }
</script>
<?php 
$this->headScript()->appendFile('/js/axis/admin/cache.js'); 
$this->setButtons(array(
    array(
        'title' => $this->translate('admin')->__('Back'),
        'onclick' => 'history.back()',
        'class' => 'alt-button'
    ),
    array(
        'title' => $this->translate('admin')->__('Disable all'),
        'onclick' => "save('disable')",
        'class' => 'alt-button'
    ),
    array(
        'title' => $this->translate('admin')->__('Enable all'),
        'onclick' => "save('enable')",
        'class' => 'button'
    ),
    array(
        'title' => $this->translate('admin')->__('Update search indexes'),
        'onclick' => "updateSearchIndex(0, 1); return false;",
        'class' => 'button'
    ),
//    array(
//        'title' => $this->translate('admin')->__('Update search indexes'),
//        'onclick' => "window.location = Axis.getUrl('catalog_index/update-search-index/'); return false;",
//        'class' => 'button'
//    ),
    array(
        'title' => $this->translate('admin')->__('Clear all'),
        'onclick' => 'clearAll()',
        'class' => 'alt-button'
    )
));
?>