<?php
$months = Zend_Locale::getTranslationList('month');
foreach ($months as $i => $value) {
    $number = sprintf('%02d', $i);
    $expires_month[$number] = $value . ' - (' . $number . ')';
}

$today = getdate();
for ($i = $today['year'], $limit = $today['year'] + 10; $i <= $limit; $i++) {
    $expires_year[$i] = $i;
}
?>

<div id="extra-fields-<?php echo $this->payment->getCode();?>" class="payment-additional" style="display:none;">
    <ul>
        <li>
            <label class="required" for="<?php echo $this->payment->getCode() ?>-cc_owner"><?php
                echo $this->translate('checkout')->__('CC Owner')
            ?><span class="required">&nbsp;*</span></label>
            <?php echo $this->formText('payment[cc_owner]', null, array(
                'autocomplete'  => 'off',
                'id'            => $this->payment->getCode() . '-cc_owner',
                'class'         => 'input-text required'
            )) ?>
        </li>
        <li>
            <label class="required" for="<?php echo $this->payment->getCode() ?>-cc_type"><?php
                echo $this->translate('checkout')->__('Credit Card Type')
            ?><span class="required">&nbsp;*</span></label>
            <?php echo $this->formSelect(
                'payment[cc_type]',
                null,
                array(
                    'class' => 'required',
                    'id'    => $this->payment->getCode() . '-cc_type'
                ),
                array_merge(array(null => 'Please Select'), $this->payment->getCCTypes())
            ) ?>
        </li>
        <li>
            <label class="required" for="<?php echo $this->payment->getCode() ?>-cc_number"><?php
                echo $this->translate('checkout')->__('CC Number')
            ?><span class="required">&nbsp;*</span></label>
            <?php echo $this->formText('payment[cc_number]', null, array(
                'autocomplete'  => 'off',
                'id'            => $this->payment->getCode() . '-cc_number',
                'class'         => 'input-text required creditcard'
            )) ?>
        </li>
        <li>
            <label class="required" for="<?php echo $this->payment->getCode() ?>-cc_expires_month"><?php
                echo $this->translate('checkout')->__('Expires Date')
            ?><span class="required">&nbsp;*</span></label>
            <?php echo
                $this->formSelect(
                    'payment[cc_expires_month]',
                    null,
                    array(
                        'class' => 'input-cc-month',
                        'id'    => $this->payment->getCode() . '-cc_expires_month'
                    ),
                    $expires_month
                )
                . '&nbsp;'
                . $this->formSelect(
                    'payment[cc_expires_year]',
                    null,
                    array(
                        'class' => 'input-cc-year',
                        'id'    => $this->payment->getCode() . '-cc_expires_year'
                    ),
                    $expires_year
                ) ?>
        </li>
        <?php if ($this->payment->config('enabledCvv')) : ?>
        <li class="cvv-row">
            <label class="required" for="<?php echo $this->payment->getCode() ?>-cc_cvv"><?php
                echo $this->translate('checkout')->__('Cvv')
            ?><span class="required">&nbsp;*</span></label>
            <?php echo $this->formText('payment[cc_cvv]', null, array(
                'autocomplete'  => 'off',
                'id'            => $this->payment->getCode() . '-cc_cvv',
                'class'         => 'input-text required input-cc-cvv'
            )) ?>
            <a class="cvv-help" href="#"><?php echo $this->translate('checkout')->__('CVV Help') ?></a>
        </li>
        <?php endif; ?>
    </ul>
</div>
