<div class="right">
    <div id="welcome">
        <span class="greeting"><?php echo $this->translate('admin')->__('Welcome')?>, <?php echo $this->box->getData('userInfo')->firstname . '  ' . $this->box->getData('userInfo')->lastname ?> </span>&nbsp;|&nbsp;
        <a href="<?php echo $this->href('auth/logout');?>"><?php echo $this->translate('account')->__('Logout') ?></a>&nbsp;|&nbsp;
        <span class="date"><?php echo $this->box->todayDate ?></span>
    </div>
    <div id="news">
        <span><?php echo $this->translate('admin')->__("%d new orders today, total %s", $this->box->orderCount, $this->box->orderTotal) ?></span>
        <a href="<?php echo $this->href('sales_order');?>"><?php echo $this->translate('account')->__('View') ?></a>&nbsp;|&nbsp;
        <span><?php echo $this->translate('admin')->__("%d new requests today", $this->box->mailCount) ?></span>
        <a href="<?php echo $this->href('contacts_index');?>"><?php echo $this->translate('account')->__('View') ?></a>
    </div>
</div>