<?php $this->headScript()->appendFile('/js/axis/admin/tag/tag.js'); ?>

<script type="text/javascript">

<?php if ($this->tagId) : ?>
    var tagId = <?php echo $this->tagId?>;
<?php endif; ?>

var menuStatus = [
<?php
    $i = 1;
    $menu = "";
    foreach (Axis_Tag_Model_Customer::getStatuses() as $value) {
        $value = addslashes($value);
        $menu .= "{
            text: '$value',
            cls: 'x-btn-text-icon',
            handler: function() {
                setStatus($i);
            }
        },\n";
        $i++;
    }
    echo substr($menu, 0, -2);
?>];

var statuses = [
<?php
$statuses = '';
foreach (Axis_Tag_Model_Customer::getStatuses() as $id => $status) {
    $status = addslashes($status);
    $statuses .= "[{$id}, '{$status}'], ";
}
echo substr($statuses, 0, -2);
?>
];
</script>

<?php echo $this->formSelect('status-combo', null, null, Axis_Tag_Model_Customer::getStatuses()); ?>
