<?php 
$this->headScript()
    ->appendFile('/js/ext-ux/multiselect/ComboSelect.js')
    ->appendFile('js/ext-axis/src/widgets/form/ComboSelect.js')
    ->appendFile('/js/axis/admin/sitemap/sitemap.js');
?>
<script type="text/javascript">

var gridSitemap, siteMapId;
<?php if ($this->sitemapId) : ?>
   sitemapId = <?php echo $this->sitemapId?>;
<?php endif; ?>

var sites = <?php echo Zend_Json_Encoder::encode($this->sitesList);?>;
var crawlers = <?php echo Zend_Json_Encoder::encode($this->crawlers);?>;
</script>