<?php if ($this->box->getData('identity')):?>
<ul class="no-bullet no-indent">
    <?php foreach ($this->box->getItems() as $_item) :
        $_title = $this->translate('account')->__($_item->getTitle());?>
        <li class="<?php echo $_item->getCssClass()?>">
            <a href="<?php echo $_item->getHref()?>" title="<?php echo $_title?>">
                <?php echo $_title?>
            </a>
        </li>
    <?php endforeach;?>
</ul>
<?php else : ?>
<form method="post" id="form-login-box" action="<?php echo $this->href('account/auth/login', true) ?>">
    <div>
        <dl>
            <dt><label for="username"><?php echo $this->translate('account')->__('Email')?></label></dt>
            <dd><input type="text" name="username" class="required email input-text"/></dd>
            <dt><label for="password"><?php echo $this->translate('account')->__('Password')?></label></dt>
            <dd><input type="password" name="password" class="required input-text"/></dd>
        </dl>
        <?php echo $this->button($this->translate('account')->__('Login'), array(
            'class' => 'button btn-login',
            'type' => 'submit'
        ), 'button') ?>
    </div>
</form>
<script type="text/javascript">
$("#form-login-box").validate();
</script>
<?php endif ?>
